### PR TITLE
rp2: Fix lost CYW43 WiFi events when using both cores.

### LINKED ISSUE #16779: RP2: Pico 2 W Not connecting with thread running
### Port, board and/or hardware

RP2 - Pico 2 W

### MicroPython version

MicroPython v1.25.0-preview.229.g0d46e45a1 on 2025-01-27; Raspberry Pi Pico 2 W with RP2350

### Reproduction

```import network
import time
import _thread
import urequests

SSID = ""
password = ""

def connect_normal():
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    wlan.connect(SSID, password)
    print("Connecting to network")

    start_time = time.time()
    while not wlan.isconnected() and time.time() - start_time < 20:
        print("Waiting for connection...")
        time.sleep(2)

    if wlan.isconnected():
        print("Connected to network")
    else:
        print("Failed to connect to network")

    print("Sleep for 2 seconds")
    time.sleep(2)
    wlan.disconnect()
    
def main_thread():
    connect_normal()

def second_thread():
    for (i) in range(10):
        print("Second thread")
        time.sleep(2)

_thread.start_new_thread(second_thread, ())
main_thread()
```

Other things tested but not working:
- Extending the 20-second time limit.
- Putting `wlan = network.WLAN(network.STA_IF)`, `wlan.active(True)`, and `wlan.connect(SSID, password)` before starting a thread.
- Switching the functions `connection_normal` and `second_thread` to run in the other thread. So the connection is made on the newly opened thread.
- Building firmware with the latest Pico SDK develop
- Adding `rp2.country("NL")` and `network.country(country)`.

### Expected behaviour

Expected to connect to the network and print `Connected to network`.

### Observed behaviour

No connection is established after the set time of 20 seconds. (Time is irrelevant as it never seems to connect). When the line `_thread.start_new_thread(second_thread, ())` is commented out, a connection is found almost every single time.

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Closes #16779. Thanks to @coencoensmeets for a clear and easy to reproduce bug report, and to @Gadgetoid for doing some deep digging to zero in on the root cause.

There's a very odd but predictable sequence of events that breaks Wi-Fi when using both cores:

1) CPU1 calls `pendsv_suspend()` - for example sleep() causes a softtimer node to be inserted, which calls `pendsv_suspend()`.
2) CYW43 sends wakeup IRQ. CPU0 GPIO IRQ handler schedules PendSV and disables the GPIO IRQ on CPU0, to re-enable after `cyw43_poll()` runs and completes.
3) CPU0 `PendSV_Handler` runs, sees pendsv is suspended, exits.
4) CPU1 calls `pendsv_resume()` and `pendsv_resume()` sees PendSV is pending and triggers it on CPU1.
5) CPU1 runs `PendSV_Handler`, runs `cyw43_poll()`, and at the end it re-enables the pin IRQ *but now on CPU1*.

However CPU1 has the overall GPIO IRQ line disabled, so the CYW43 interrupt never runs again...

Fix is to specifically only enable the GPIO interrupt on CPU0. This isn't supported in pico-sdk but appears to be supported by the hardware.

Plus two follow-up commits:

* Refactor out the `cyw43_has_pending` global flag to instead be a check of the pendsv table. This was necessary for the previous version of this PR. Not necessary now, but seems like a worthwhile change.
* Enable PendSV interrupt at the correct priority on both CPUs, and even if CYW43 is not in use. Also adds some comments in PendSV explaining how it can run on either CPU.

*This work was funded through GitHub Sponsors.*

### Testing

* Ran the test Python program from the linked issue on both RPI_PICO_W and RPI_PICO2_W boards, verified the problem goes away.
* Ran the multi_wlan test between RPI_PICO_W and RPI_PICO2_W and an ESP32, verified tests still pass.

### Trade-offs and Alternatives

* First version of this PR instead changed the interrupt to rising edge, so it didn't need to be disabled. This appears to work fine, and simplifies the code, but actually the CYW43 interrupt pin on RP2 is muxed with the data pin so the GPIO edge interrupt was triggering spuriously at a very high frequency. Oops!
* @Gadgetoid has a PR #16788 which adds support for CPU affinity in PendSV callbacks. We could add this support, although we don't really need the feature (everything that calls `pendsv_schedule_dispatch()` runs on CPU0).
* As @Gadgetoid also suggested in #16788, we could change PendSV to only ever fire on CPU0. In fact, comments in pendsv.c suggest that's the current expectation. I actually implemented this fix first, see https://github.com/projectgus/micropython/commit/47723da831afb4d2bdd7484c8ab8537f986a6339 . That is still more complex than this fix as it needs a cross-core PendSV trigger for when CPU1 does `pendsv_resume()`. However it might be easier to reason about overall.

### CODE REVIEW

**Comment by projectgus** [comment]
> * hange PendSV to only ever fire on CPU0. In fact, comments in pendsv.c suggest that's the current expectation

I've pushed another commit here to update these comments, and also to ensure PendSV runs at the same priority on CPU0 and CPU1.

**Comment by projectgus** [comment]
@dpgeorge let me know that the HOST_WAKE line on the rp2 is muxed with the (bidirectional) SPI data line. So with this PR the gpio irq triggers many times unnecessarily while `cyw43_poll` is running...

image
(Image is from toggling a GPIO in the `gpio_irq_handler()` network function.)

Will need to rethink...

**Comment by projectgus** [comment]
New version pushed which keeps the level-triggered interrupt but hand-rolls a function to only ever enable it on CPU0.

Have also a raised a feature request in pico-sdk to have this in the GPIO API: https://github.com/raspberrypi/pico-sdk/issues/2354

File: ports/rp2/pendsv.h [hunk 1]
```diff
@@ -27,6 +27,7 @@
 #define MICROPY_INCLUDED_RP2_PENDSV_H
 
 #include <stddef.h>
+#include "hardware/irq.h"
```
Comment (dpgeorge) [inline ports/rp2/pendsv.h:30]: I don't think this include is needed (or maybe needs to be moved to `pendsv.c`).

**Comment by dpgeorge** [comment]
The latest changes look really good.  I will test them.

File: ports/rp2/pendsv.h (hunk 1 above)
Comment (dpgeorge) [reply ports/rp2/pendsv.h:30]: > This header has `#define IRQ_PRI_PENDSV PICO_LOWEST_IRQ_PRIORITY` in it, so I added this on the basis of "include what you use".

Ah, I see.  That makes sense.

> But I now realise the macro define could also be moved to pendsv.c, as (as of this PR) this is the only file which uses it.

Yes indeed it could be moved.  I'm happy either way (move or keep here).

Comment (projectgus) [reply ports/rp2/pendsv.h]: Have moved!

**Review by dpgeorge — APPROVED** [review]

**Comment by dpgeorge** [comment]
Thanks for splitting this up into a set of very clean, independent commits.
