### PR TITLE
esp32/machine_hw_spi: Reject invalid number of bits in constructor.

### LINKED ISSUE #5910: ESP32 SPI bits=0 results in IntegerDivideByZero
Simple typo led to this discover...

```
hspi = SPI(2, 10000000, sck=SCK, mosi=MOS, phase=0, bits=0, firstbit=0)
```

Full dump
```
Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.
Core 1 register dump:
PC      : 0x400f974f  PS      : 0x00060530  A0      : 0x801b6510  A1      : 0x3ffd0130  
A2      : 0x3ffc20f0  A3      : 0x00000088  A4      : 0x3ffe5870  A5      : 0x00000000  
A6      : 0x00000440  A7      : 0xfffffffe  A8      : 0x00000000  A9      : 0x3ffd0120  
A10     : 0x3ffd0130  A11     : 0x00000000  A12     : 0x00000028  A13     : 0x3ffd0158  
A14     : 0x0000002a  A15     : 0x00000002  SAR     : 0x00000006  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x400f974c:0x3ffd0130 0x401b650d:0x3ffd0180 0x400f1803:0x3ffd01a0 0x400e3751:0x3ffd01d0 0x400df7d9:0x3ffd01f0 0x400df8fe:0x3ffd0210 0x400ed281:0x3ffd0230 0x400e38a8:0x3ffd02d0 0x400df7d9:0x3ffd0300 0x400df802:0x3ffd0320 0x400df86f:0x3ffd0340 0x400ea4ed:0x3ffd03d0 0x400ea82a:0x3ffd0400 0x400df97e:0x3ffd04e0 0x400ed51c:0x3ffd0520 0x400e38a8:0x3ffd05c0 0x400df7d9:0x3ffd0620 0x400df802:0x3ffd0640 0x40103b84:0x3ffd0660 0x40103dad:0x3ffd06f0 0x40103e0b:0x3ffd0710 0x400f5c8a:0x3ffd0730 0x4008fc19:0x3ffd0760

Rebooting...
```

Built against 740946736

### PR DESCRIPTION
**Pull request by agatti**
### Summary

This commit adds an extra bit of parameters validation to the SPI bus constructor on ESP32.  Passing 0 as the number of bits would trigger a division by zero error when performing read/write operations on an SPI bus created in such a fashion.

This fixes #5910.

### Testing

This was tested locally on an ESP32-D0WD:

```
MicroPython v1.24.0-preview.363.g17d823445.dirty on 2024-10-01; Generic ESP32 module with ESP32
Type "help()" for more information.
>>> import machine
>>> machine.SPI(2, 10000000, sck=10, mosi=20, phase=0, bits=0, firstbit=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid number of bits (0)
>>> machine.SPI(2, 10000000, sck=10, mosi=20, phase=0, bits=-2, firstbit=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid number of bits (-2)
>>> machine.SPI(2, 10000000, sck=10, mosi=20, phase=0, bits=-1, firstbit=0)
SPI(id=2, baudrate=10000000, polarity=0, phase=0, bits=8, firstbit=0, sck=10, mosi=20, miso=19)
>>> 
```

### Trade-offs and Alternatives

This PR fixes the issue on ESP32, but maybe this is still a problems on other ports.  I do not have many non-ESP32 boards that are currently supported around here so I can only claim this fixes the ESP32 version of the bug.  Given that the bus instances are constructed in platform-specific code then I'd have to fix all of them if they have this specific issue.  I've got no problem in doing the fix on other platforms but I may not be able to perform code validation.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I think this should be checked in `machine_hw_spi_init_internal()`, otherwise you can still make it crash via `spi.init(bits=0)`.

File: ports/esp32/machine_hw_spi.c [hunk 1]
```diff
@@ -447,6 +447,10 @@ mp_obj_t machine_hw_spi_make_new(const mp_obj_type_t *type, size_t n_args, size_
         }
     }
 
+    if (args[ARG_bits].u_int != -1 && args[ARG_bits].u_int <= 0) {
+        mp_raise_msg_varg(&mp_type_ValueError, MP_ERROR_TEXT("Invalid number of bits (%d)"), args[ARG_bits].u_int);
```
Comment (dpgeorge) [inline ports/esp32/machine_hw_spi.c:451]: I suggest a message like "invalid bits %d", or just "invalid bits".  The latter matches `adc.c` and `machine_i2s.c` error messages.

**Comment by agatti** [comment]
This should be sorted now, I also changed the error message to be in line with the other two cases you mentioned, thanks!

**Review by dpgeorge — APPROVED** [review]

**Comment by dpgeorge** [comment]
Thanks for updating, looks good now.
