### PR TITLE
py/nlrx64: Mark nlr_push() as naked function when possible.

### LINKED ISSUE #12421: embedding example segfaults under gcc with no optimizations
Hi,

I recently ran around in circles trying to find out why the embedded port was failing to run in my application, and eventually tracked it down to an issue when compiling with 0 optimizations in the library.

to reproduce:

    cd examples/embedding
    make -f micropython_embed.mk
    # Swap the optimization level to 0 in the Makefile
    sed -i s,-Og,-O0,g Makefile
    make

The embed application now segfaults on launch

    $ ./embed 
    Segmentation fault

This is from the released source tarball: micropython-1.20.0.tar.xz 
GCC 9.3.1 on Centos 7.9.2009 , under redhat's devtoolset-9

### PR DESCRIPTION
**Pull request by projectgus**
Alternative to #12433 that might also simplify the macOS builds, and makes nlrx64.c more similar to nlrx86.c.

I'm aware that naked functions have a history of being a nuisance in the NLR code though (#3484, etc) so maybe this is not a good option in some way.

- Fixes situation where building embedded MicroPython with -O0 and MICROPY_NLR_X64 crashes at runtime (due to nlr_push pushing the frame pointer register EBP). Closes #12421.

- Allows removing the macOS tweak to undo pushing EBP onto the stack in the generated function prelude.

## TODOs

* [x] Test the unix port on macOS x86-64.

### CODE REVIEW

File: py/nlrx64.c [hunk 1]
```diff
@@ -35,6 +35,16 @@
 
 __attribute__((used)) unsigned int nlr_push_tail(nlr_buf_t *nlr);
 
+#if !MICROPY_NLR_OS_WINDOWS
+#if defined(__clang__) || (defined(__GNUC__) && __GNUC__ >= 8)
```
Comment (projectgus) [inline py/nlrx64.c:39]: nlrx86.c only uses "naked" for GCC >= 8 and never for Clang. However, Compiler Explorer suggests that the naked attribute works the same in Clang since 3.6 (2014).

**Comment by projectgus** [comment]
The [CI test job runs on macOS x64](https://github.com/micropython/micropython/actions/runs/6166832440/job/16737002562)  (can see it by expanding the "source ci.sh" step that logs some library paths), so this change works as expected on macOS.

File: py/nlrx64.c [hunk 2]
```diff
@@ -35,8 +35,27 @@
...
+#if !defined(USE_NAKED)
+#define USE_NAKED 0
+#endif
+
+#if USE_NAKED
+// nlr_push prelude should never push frame pointer register ebp onto the stack
+__attribute__((naked))
+#endif
 unsigned int nlr_push(nlr_buf_t *nlr) {
+    #if !USE_NAKED
```
Comment (dpgeorge) [inline py/nlrx64.c:56]: Is this guard needed?  The x86 version doesn't have it.

The argument is never used, so doesn't hurt to always have this void statement.

OTOH, I'm guessing that naked functions should not have any code in them except asm statements.

Comment (projectgus) [reply py/nlrx64.c:56]: The guard's needed here for Clang, it's more strict about the "nothing but asm statements" rule than gcc. (https://gcc.godbolt.org/z/fWjTT34aY)

nlrx86.c doesn't set `USE_NAKED` for Clang, even though I think it could (as per inline comment above.)

Comment (projectgus) [reply py/nlrx64.c:56]: (I can update nlrx86.c in this PR as well if you like. My only real concern would be that x86 probably has a slightly older range of compiler versions targeting it.)

Comment (dpgeorge) [reply py/nlrx64.c:56]: OK, thanks for the clarification.

Let's leave x86 as-is.
