### PR TITLE
ports: Raise an error at a negative argument of os.urandom().

### LINKED ISSUE #18825: os.urandom(-1) crash
### Port, board and/or hardware

unix

### MicroPython version

MicroPython v1.28.0-preview.174.ga8b71559cf on 2026-02-16; linux [GCC 15.2.0] version

### Reproduction

```python
import os
os.urandom(-1)
```

### Expected behaviour

ValueError: negative argument not allowed

### Observed behaviour

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==29603==ERROR: AddressSanitizer: SEGV on unknown address 0x7ffa15c00000 (pc 0x7ffa165194ab bp 0x7ffc170fef90 sp 0x7ffc170fef30 T0)
==29603==The signal is caused by a WRITE memory access.
    #0 0x7ffa165194ab  (linux-vdso.so.1+0x14ab) (BuildId: 9b63024b6069edc1f3baef9d1ce5d39a51e32768)
    #1 0x7ffa1564df0e in getrandom_vdso ../sysdeps/unix/sysv/linux/getrandom.c:211

==29603==Register values:
rax = 0x0000000000000000  rbx = 0x000000007ffff000  rcx = 0x0000000001ffa00f  rdx = 0x00007ffc170fef60  
rdi = 0x00007ffa15bfffe0  rsi = 0x00007ffa1637cf60  rbp = 0x00007ffc170fef90  rsp = 0x00007ffc170fef30  
 r8 = 0x000000007ffff000   r9 = 0xffffffffffffffff  r10 = 0x00007ffa1637cf00  r11 = 0x0000000000000246  
r12 = 0x00007ffa15a813a0  r13 = 0xffffffffffffffff  r14 = 0x00007ffa1637cf00  r15 = 0x0000000001ffffc0  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (linux-vdso.so.1+0x14ab) (BuildId: 9b63024b6069edc1f3baef9d1ce5d39a51e32768) 
==29603==ABORTING

```

### Additional Information

No, I've provided everything above.

Credit: Yuan (@Reset816) and me.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by robert-hh**
### Summary
Raise an error at a negative argument of os.urandom().

### Testing

Tested for the cc3200, esp32, esp8266, mimxrt, nrf, rp2, samd, stm32 and unix ports. Compiled for the alif and the renesas port but not tested lacking suitable boards.

Argument values -1, 0, 3

### Trade-offs and Alternatives

The PR repeats the same few lines of code for each port. That looks not nice. I tried to factor out the common code part if mp_os_urandom(), but that fails for quite a few build vaiants. To be tested further, if needed.

### CODE REVIEW

File: ports/mimxrt/modos.c [hunk 1]
```diff
@@ -102,9 +102,11 @@ uint32_t trng_random_u32(void) {
 static mp_obj_t mp_os_urandom(mp_obj_t num) {
     mp_int_t n = mp_obj_get_int(num);
     vstr_t vstr;
+    if (n < 0) {
+        mp_raise_ValueError(MP_ERROR_TEXT("argument < 0"));
+    }
     vstr_init_len(&vstr, n);
 
-    trng_start();
```
Comment (mimi89999) [inline ports/mimxrt/modos.c:107]: Why was this line removed?

Comment (robert-hh) [reply ports/mimxrt/modos.c:107]: Because trng_start() is called again in trng_random_data(). So it was obsolete.

Comment (mimi89999) [reply ports/mimxrt/modos.c:107]: I see, but it seems like an unrelated change to the subject of the commit

Comment (robert-hh) [reply ports/mimxrt/modos.c:107]: It is. Just a windfall benefit.

**Comment by Josverl** [comment]
@robert-hh ,
I notice a test missing for the new error, 
I also wonder if it would not be sufficient to raise just a `ValueError` and omit the text. That should save some bytes.
Or the error should be matched to CPython's .

```py
# 3.11.9
>>> os.urandom(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative argument not allowed
```

**Comment by robert-hh** [comment]
I had considered both just having `ValueError` for small flash devices or using the CPython error message and ended with the actual text as compromise for lower complexity.

**Comment by robert-hh** [comment]
By the way: I did not change the Windows port because I could not spot the source files. The ports/windows directory does not have many of these. I used to build Windows versions > 7 years ago, and it seems I lost track for that port.

**Comment by Josverl** [comment]
It does have the same issue in 1.27 , but afaikt it uses the code from the Unix port for this, so your fix should work.
Adding a test to CI will help verify. I'll try to find time to test.

**Comment by dpgeorge** [comment]
> The PR repeats the same few lines of code for each port. That looks not nice. I tried to factor out the common code part if mp_os_urandom(),

I think we should do that first.  All existing port-specific implementations look like this:
```c
static mp_obj_t mp_os_urandom(mp_obj_t num) {
    mp_int_t n = mp_obj_get_int(num);
    vstr_t vstr;
    vstr_init_len(&vstr, n);
    // port specific code to fill vstr.buf
    return mp_obj_new_bytes_from_vstr(&vstr);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mp_os_urandom_obj, mp_os_urandom);
```
so could factor that code into `extmod/modos.c` as something like:
```c
static mp_obj_t mp_os_urandom(mp_obj_t num) {
    mp_int_t n = mp_obj_get_int(num);
    vstr_t vstr;
    vstr_init_len(&vstr, n);
    mp_os_urandom_bytes(n, vstr.buf);
    return mp_obj_new_bytes_from_vstr(&vstr);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mp_os_urandom_obj, mp_os_urandom);
```
and then each port defines `void mp_os_urandom_bytes(size_t n, uint8_t *buf)` in its `modos.c`.

@robert-hh would you like to do that?

**Comment by projectgus** [comment]
> and then each port defines void `mp_os_urandom_bytes(size_t n, uint8_t *buf)` in its `modos.c`.

If we do this then we can also probably refactor the other places in each port which fill a buffer with random bytes (i.e. similar to the changes in #18834) to call that single helper function, maybe save a little more code size.

**Comment by dpgeorge** [comment]
> If we do this then we can also probably refactor the other places in each port which fill a buffer with random bytes

Yes, good idea.  In that case maybe copy what the unix port already has: `mp_hal_get_random()`.

**Comment by robert-hh** [comment]
> @robert-hh would you like to do that?

@dpgeorge Sure. I had already prepared it, will call that function providing the raw values `mp_hal_get_random()` and put it into mphalport.c.

**Comment by robert-hh** [comment]
@dpgeorge I hav a question about an implementation detail, before changing 11 ports. The unix port defines `void mp_hal_get_random(size_t n, void *buf);`. Shouldn't it be better `void mp_hal_get_random(size_t n, uint8_t *buf);`, because that's what the ports do in their implementation of os.urandom().

**Comment by dpgeorge** [comment]
> Shouldn't it be better `void mp_hal_get_random(size_t n, uint8_t *buf)`

Yes, change the unix port to `uint8_t *buf` looks better (and I don't see any downsides of that change).

**Comment by robert-hh** [comment]
@dpgeorge os.orandom() is now factored out. It ended up with quite a few changed files, but the changes are similar for all ports. The actual random numbers are provided by mp_hal_get_random() of each port. The respective implementation for the ports is moved to mphalport.x or equivalent, except for MIMXRT and SAMD, because theses have more than on instance of mp_hal_get_random() calling another function. That is better kept in a single place.

The PR still has two commits for visibility during the review, but the first one should be squashed. Using `mp_hal_get_random()` at other places in the code is not yet included. That can be done when the actual state is clean.

File: extmod/modos.c [hunk 2]
```diff
@@ -145,6 +145,22 @@ static mp_obj_t mp_os_dupterm_notify(mp_obj_t obj_in) {
 static MP_DEFINE_CONST_FUN_OBJ_1(mp_os_dupterm_notify_obj, mp_os_dupterm_notify);
 #endif
 
+#if MICROPY_PY_OS_URANDOM
+// mp_os_urandom_make() actually creates the random numbers. It
+// is usually defined in the port's modos.c file.
```
Comment (dpgeorge) [inline extmod/modos.c]: Suggest changing to something like:
```
// This wraps the port-specific mp_hal_get_random(), which is usually defined in mphalport.c.
```

File: extmod/modos.c [hunk 3]
```diff
@@ -145,6 +145,22 @@ static mp_obj_t mp_os_dupterm_notify(mp_obj_t obj_in) {
...
+static mp_obj_t mp_os_urandom(mp_obj_t num) {
+    mp_int_t n = mp_obj_get_int(num);
+    if (n < 0) {
+        mp_raise_ValueError(MP_ERROR_TEXT("argument < 0"));
```
Comment (dpgeorge) [inline extmod/modos.c]: I suggest a NULL error message, just to keep the code size down for this relatively uncommon path.

**Review by dpgeorge — COMMENTED** [review]
It would be good if the two commits could be swapped around: first commit does the refactoring, second commit adds the <0 check.

File: extmod/modos.c (hunk 3 above)
Comment (robert-hh) [reply extmod/modos.c]: Done

File: extmod/modos.c (hunk 2 above)
Comment (robert-hh) [reply extmod/modos.c]: Doen

**Comment by robert-hh** [comment]
The suggested changes are made.

I spotted at least one typical place to use mp_hal_get_ramdom(), which is the function mbedtls_hardware_poll() in mbedtls_port.c. It is changed already for MIMXRT, which used the random number generation from modos already before. There are four more ports where this could be used. Maybe this function can then be moved to another place/file, when it gets port-agnostic.

**Comment by dpgeorge** [comment]
> I spotted at least one typical place to use mp_hal_get_ramdom(), which is the function mbedtls_hardware_poll() in mbedtls_port.c. It is changed already for MIMXRT, which used the random number generation from modos already before. There are four more ports where this could be used. Maybe this function can then be moved to another place/file, when it gets port-agnostic.

Yes, that sounds good.  Let's leave it for a follow up PR.

**Comment by dpgeorge** [comment]
I added a test for `os.urandom()` which checks negative arguments (as well as 0 and positive values).

**Comment by robert-hh** [comment]
Thanks for adding the test. I was wondering whether a .exp file is missing. But it seems that the approach has changed.

**Comment by dpgeorge** [comment]
> I was wondering whether a .exp file is missing. But it seems that the approach has changed.

The approach is still the same.  In this case the behaviour matches CPython, so the exp file is generated dynamically as the test is run, via CPython.

**Review by dpgeorge — APPROVED** [review]
This looks good, it's a really nice clean up / consolidation across the ports.

**Comment by robert-hh** [comment]
Thank you very much.

**Comment by projectgus** [comment]
Thanks @robert-hh! This is indeed a very nice consolidation to have, much appreciated.
