### PR TITLE
rp2: fix atomic section

### LINKED ISSUE #12980: _thread module freezing whole device (RPI_PICO_W)
### Summary
When using firmware built from the master branch calling` _thread.start_new_thread` freezes the whole machine. v1.22.0-preview and earlier works as expected.

Using Raspberry Pi Pico W.

I went back to find the commit where it breaks, and i found the breaking point:  bcbdee235719d459a4cd60d51021454fba54cd0f
- 2d363a23cb9e825200e772f973eab921a69e0646 still works
- bcbdee235719d459a4cd60d51021454fba54cd0f does not work anymore

### Scenario
Im using a **Raspberry Pi Pico W** with firmware built from the repository (make etc.) In my application, right at the start of boot.py I started a process on the second thread that constantly measured the orientation, then continued as normal, but yesterday the whole program started freezing. 

After some testing I found out that calling `_thread.start_new_thread(test_function, ()) ` freezes the machine, it cannot be stopped with ctrl-c or any other method.

I tested with this file, then importing and running test()

```
import _thread

def test1():
    for i in  range(4):
        print(f"test1-{i}")

def test2():
    for i in  range(4):
        print(f"test2-{i}")

def test():
    print("Main thread:")
    test1()

    print("In second thread:")
    _thread.start_new_thread(test2, ())
    print("Main thread again:")
    test1()
```

With  2d363a23cb9e825200e772f973eab921a69e0646 and earlier I get the expected:
```
Main thread:
test1-0
test1-1
test1-2
test1-3
In second thread:
Main thread again:
test2-0
test1-0
test2-1
test1-1
test2-2
test1-2
test2-3
test1-3

```
But after **bcbdee235719d459a4cd60d51021454fba54cd0f**  I get: 
image
image

then freezes completely. Power cycling does make the device responsive again. 

Sorry about the format, first time creating an issue.

### LINKED ISSUE #13288: V1.22 creating new thread leads to hangup
Dear micropython developers,

this morning I found about micropython V1.22 and tried this on my Raspberry Pico (non W). But unfortunately I had to find out that my programs stop when the second thread is created.

consider this boot.py to reproduce the issue:
```python
import _thread
import machine 
import asyncio

from time import sleep, sleep_ms


async def thread1task():
    print("thread 1 started")
    while True:
        print("thread 1 talking ... ")
        await asyncio.sleep(1)
        
def thread2task():
    print("thread 2 started")
    while True:
        print("thread 2 talking ... ")
        sleep(1)


if __name__ == "__main__":
    try:
        loop = asyncio.get_event_loop()
        messagestart = const(">> starting script in ... ")
        print(messagestart + f"3")
        sleep(1)
        print(messagestart + f"2")
        sleep(1)
        print(messagestart + f"1")
        sleep(1)
        print(">> Loop is starting")


        taskobj = loop.create_task(thread1task())
        print(">> starting second thread...")
        _thread.start_new_thread(thread2task,())
        print(">> running loop ...")

        loop.run_forever()
    except KeyboardInterrupt:
        loop.stop()
        _thread.exit() # does not work, code hangs
        print(f"INTERRUPTED")
```

The hangup is not always at the exact same spot, but the "most" debug output I could receive was:
```
MPY: soft reboot
>> starting script in ... 3
>> starting script in ... 2
>> starting script in ... 1
>> Loop is starting
>> starting second thread...
>> running loop ...thread 2 started

thread 2 talking ...
```

After that the serial port is blocked, device does not react to CTRL+C or any other keys.

Executing the code above with V1.21 has no issues and runs forever as expected.

### PR DESCRIPTION
**Pull request by dpgeorge**
This is an attempt to fix #12980 and #13288.

~~There are two fixes to the `MICROPY_BEGIN_ATOMIC_SECTION`/`
MICROPY_END_ATOMIC_SECTION` on the rp2 port:~~
- ~~Use a recursive mutex to prevent deadlocks on the same thread, in the case an IRQ races against the thread level (on the same core) when acquiring the atomic section (mutex may be taken but IRQs not yet disabled, then the IRQ waits forever trying to acquire the mutux).~~
- ~~Unlock the mutex if it was locked, not if `core1_entry` is still non-null, to fix the case where the second core finishes (and sets `core1_entry` to `NULL`) while the first core is in the middle of an atomic operation.~~

Edit: the two changes are now:
1. split out multicore lockout handling so it's only done when doing a flash erase/write
2. change the ATOMIC_SECTION macros so they use new mutex enter/exit functions that also disable/restore interrupts (atomically).

### CODE REVIEW

**Comment by mendenm** [comment]
It works!  At least  the simple test  script runs both processors and reports results form them.

Excellent.

File: ports/rp2/mpthreadport.c [hunk 1]
```diff
@@ -45,16 +45,15 @@ STATIC uint32_t *core1_stack = NULL;
...
 uint32_t mp_thread_begin_atomic_section(void) {
     if (core1_entry) {
         // When both cores are executing, we also need to provide
         // full mutual exclusion.
-        mp_thread_mutex_lock(&atomic_mutex, 1);
-        // In case this atomic section is for flash access, then
-        // suspend the other core.
-        multicore_lockout_start_blocking();
+        recursive_mutex_enter_blocking(&atomic_mutex);
+        ++atomic_taken;
```
Comment (projectgus) [inline ports/rp2/mpthreadport.c:56]: Doesn't `recursive_mutex_enter_blocking()` provide this recursion count function?

**Comment by dpgeorge** [comment]
I have changed this to use a new set of mutex functions that also disable/restore interrupts when obtaining/releasing the mutex.

**Comment by projectgus** [comment]
New approach looks good to me!
