### PR TITLE
py/modthread.c: Initialise nlr_jump_callback_top on threads.

### LINKED ISSUE #12695: nlr_jump in MPY 1.21 causing ESP32 exception when catch exception executed in other micropython threads, not main thread REPL
nlr_call_jump_callbacks causing this issue. Please refer to my detail issue description here.

### Discussed in https://github.com/orgs/micropython/discussions/12690

<div type='discussions-op-text'>

<sup>Originally posted by **bhcuong2008** October 15, 2023</sup>
I have 3 test cases as below with MicroPython v1.21.0 on ESP32, also in my program.

1. Test case 1, I run this code, and the result as expected.
```
nlr_buf_t nlr;
if(nlr_push(&nlr) == 0) { 
  MP_CMOS_DICT = mp_load_global(MP_QSTR_CMOS);
  nlr_pop();
} else {
  mp_obj_print_exception(&mp_plat_print, (mp_obj_t)nlr.ret_val);
}
```
It prompts `NameError: name 'CMOS' isn't defined` as expected behavior in MicroPython.

2. Test case 2, the code is
```
MP_CMOS_DICT  = mp_const_none;
nlr_buf_t nlr;
if(nlr_push(&nlr) == 0) {
  mp_obj_t mp_fn = mp_load_attr(MP_CMOS_DICT, MP_QSTR_clear);
  mp_call_function_0(mp_fn);
  nlr_pop();
} else {
  mp_obj_print_exception(&mp_plat_print, (mp_obj_t)nlr.ret_val);
}
```
I can't catch python exception in C code. Exception decoder is:
```
0x401b4270: nlr_pop_jump_callback at micropython/py/nlr.c line 63
0x401b4297: nlr_call_jump_callbacks at micropython/py/nlr.c line 79
0x401b42bf: nlr_jump at micropython/py/nlrsetjmp.c line 32
0x401c0e93: mp_raise_msg_varg at micropython/py/runtime.c line 1676
0x401c11c9: mp_load_method at micropython/py/runtime.c line 1233
0x401c11d9: mp_load_attr at micropython/py/runtime.c line 1054
```
It can catch exception, but failed at `nlr_pop_jump_callback , *top = (*top)->prev;`, causing ESP32 exception and restart.

3. If I test in Micropython environment REPL,
```
CMOS = None
CMOS.clear 
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'clear'
```
So, in micropython env REPL, it can catch exception as expected. I think test case 2 must be the same. It must prompt `AttributeError: 'NoneType' object has no attribute 'clear'`, and not causing ESP exception LoadProhibited.

So what's wrong with my C code in test case 2?

Thanks,
Cuong.</div>

### PR DESCRIPTION
**Pull request by jimmo**
This should fix #12695 -- @bhcuong2008 could you please test and see if it solves your problem?

---

The main thread gets this because the thread state is in bss, but subsequent threads need this field to be initialised.

Also added a note to mpstate.h to help avoid missing this in the future.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

File: py/modthread.c [hunk 1]
```diff
@@ -175,6 +175,7 @@ STATIC void *thread_entry(void *args_in) {
     ts.gc_lock_depth = 0;
 
     ts.mp_pending_exception = MP_OBJ_NULL;
+    ts.nlr_jump_callback_top = NULL;
```
Comment (dpgeorge) [inline py/modthread.c:178]: This should go before `mp_pending_exception`, to match the order in the state struct definition.

Comment (jimmo) [reply py/modthread.c:177]: Done

**Comment by bhcuong2008** [comment]
@jimmo It's great. It works fine now, both for threads from MicroPython and my C code. Thank u so much.

**Comment by dpgeorge** [comment]
@bhcuong2008 thanks for testing and confirming the fix.
