### PR TITLE
esp32: Fix espnow rate setting, add constants and tests for ESP-NOW rates and Wi-Fi LR mode.

### LINKED ISSUE #18217: Changing espnow rate fails on IDFv5.4.2
### Port, board and/or hardware

ESP32, ESP32C3

### MicroPython version

1.26.1

### Reproduction

Run this snippet:
```python
import espnow
import network
sta = network.WLAN(network.STA_IF)
sta.active(True)
e = espnow.ESPNow()
e.config(rate=0x2A)
```

### Expected behaviour

It should be executed successfully without any exceptions being raised.

### Observed behaviour

An OSError will be raised:  `OSError: [Errno 1] EPERM: ESP_FAIL`

### Additional Information

It seems the problem is related to IDF v5.4.2. I've rebuilt micropython against IDF v5.4.1 and everything worked correctly. 

### Code of Conduct

Yes, I agree

### LINKED ISSUE #18311: Changing espnow rate fails on 1.26.1
### Port, board and/or hardware

ESP32-C3 Super Mini

### MicroPython version

(sysname='esp32', nodename='esp32', release='1.26.1', version='v1.26.1 on 2025-09-11', machine='ESP32C3 module with ESP32C3')

### Reproduction

```python
import os

from espnow import ESPNow
from network import AP_IF, STA_IF, WLAN

print(os.uname())
try:
    print(f'INIT start')
    if_ap = WLAN(AP_IF)
    if_ap.active(False)

    if_sta = WLAN(STA_IF)
    if_sta.active(True)
    if_sta.config(protocol=8)  # WIFI_PROTOCOL_LR

    esp_now = ESPNow()
    esp_now.active(True)
    esp_now.config(rate=0x29)  # WIFI_PHY_RATE_LORA_250K
    print('INIT complete')
except Exception as e:
    print(e)
```

### Expected behaviour

```
MPY: soft reboot
(sysname='esp32', nodename='esp32', release='1.24.1', version='v1.24.1 on 2024-11-29', machine='ESP32C3 module with ESP32C3')
INIT start
INIT complete
```

### Observed behaviour

```
MPY: soft reboot
(sysname='esp32', nodename='esp32', release='1.26.1', version='v1.26.1 on 2025-09-11', machine='ESP32C3 module with ESP32C3')
INIT start
[Errno 1] EPERM: ESP_FAIL
```

### Additional Information

Micropython 1.24.1 is working
Micropython 1.26.1 is NOT working.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

* Fix a failure to set data rate introduced when updating to IDF v5.4.x. Fixes #18311  and Fixes #18217. Previously the API silently accepted setting the data rate on an inactive interface, but now we have to check if AP and STA are each started before setting.
* Add a test case for data rate setting.
* While writing the test case I realised these APIs rely on "magic numbers", including some numbers that may change in ESP-IDF updates. Added some constants for ESP-NOW data rates and the Espressif Wi-Fi "long range" mode, documented them, and then used them in the new test.

### Testing

* Ran the new test on ESP32, ESP32-C3 and ESP32-S3 successfully.
* ESP32-C2 this feature works but LR mode isn't supported, so the test is skipped.
* ESP32-C6 cannot set the transmit data rate as we're still using the deprecated data rate API. See below.

Note that two of the existing `multi_espnow` tests currently fail on master and in this PR since IDF v5.4.x, see comments https://github.com/micropython/micropython/pull/16737#pullrequestreview-3485171381 and https://github.com/micropython/micropython/pull/16737#issuecomment-3555185710. These failures shouldn't effect most MicroPython espnow users.

### Future Work

As discussed in https://github.com/micropython/micropython/issues/18217#issuecomment-3380616894 - the API we're using to set the data rate is deprecated and not supported at all on ESP32-C6, and will be removed in ESP-IDF V6.0 (currently in beta).

However, this is a bigger change (the new API takes a more complex data structure) that we can make in follow-up work.

### CODE REVIEW

File: ports/esp32/modespnow.c [hunk 1]
```diff
@@ -197,7 +207,6 @@ static mp_obj_t espnow_init(mp_obj_t _) {
         self->recv_buffer = m_new_obj(ringbuf_t);
         ringbuf_alloc(self->recv_buffer, self->recv_buffer_size);
 
-        esp_initialise_wifi();  // Call the wifi init code in network_wlan.c
```
Comment (dpgeorge) [inline ports/esp32/modespnow.c:200]: I see these init functions have been removed.  That seems fine, because the docs clearly state that you must activate WiFi AP and/or STA before activating ESPNOW.

Although, the multi tests actually activate ESPNOW before activating WiFi...!  They still work, so don't need changing, but might be worth changing them (in a follow-up PR) so they serve as good examples.

**Comment by dpgeorge** [comment]
Thanks for this.  I tested with ESP32-C3 and ESP32-S3 and the multitests pass in both directions, except for `20_send_echo.py` which always fails with `ValueError: ESPNow.recv(): buffer error`.  But, as you say, that's a separate issue.

**Review by dpgeorge — APPROVED** [review]
The added constants do make sense to have, will make it a lot easier for people to configure the protocol and rate.

And thanks for the docs update and the new test.  Really good.
