### PR TITLE
extmod/modframebuf: Validate framebuf bounds against buffer.

### LINKED ISSUE #12562: null-dereference in {mvlsb,rgb565}_fill_rect
# Description

We found a null-dereference in `mvlsb_fill_rect` and `rgb565_fill_rect` while MicroPython is operating on a `FrameBuffer` instance with an improper fill value to `fill()`. All mvlsb-related PoCs created a `FrameBuffer` instance with `FrameBuffer1()`, while all rgb565-related ones used `FrameBuffer()`.

[poc-fill_rect.zip](https://github.com/micropython/micropython/files/12782344/poc-fill_rect.zip)

We also found another null-dereference in `mvlsb_getpixel` and `rgb565_getpixel`. The PoCs are very similar to the PoCs above, except for using `pixel()` instead of `fill()` before the crash.

[poc-getpixel.zip](https://github.com/micropython/micropython/files/12782345/poc-getpixel.zip)

# Proof of Concept

```
$ # build unix port with ASAN, at the root source code directory.
$ export CC=clang
$ export CXX=clang++
$ export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
$ export CXXFLAGS=$CFLAGS
$ export LDFLAGS=$CFLAGS
$ export DEBUG=1
$ make -C mpy-cross -j
$ make -C ports/unix -j all lib
$
$ # run a poc.
$ export ASAN_OPTIONS="detect_leaks=0"
$ ./ports/unix/build-standard/micropython <poc_file>
```

# Environment

Ubuntu 20.04
Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Memory: 64 GB

# Affected Version

v1.20.0 (commit a3862e726, latest as of 2023-09-26)
v1.20.0 (commit 813d559bc, 2023-06-19)
Discovered in the UNIX port version.

### PR DESCRIPTION
**Pull request by jimmo**
Fixes #12562 and #12563. cc @gwangmu

I'm not sure why FrameBuffer never validated these arguments, I guess maybe as a code size optimisation but I think this is a useful thing to guard against accidental mistakes and improve usability / reduce confusion as debugging "why doesn't the display look right" can be quite difficult.

Also fixes the length calculation in `framebuf_get_buffer` which was completely wrong for most formats as it did not take into account the bits-per-pixel. (Edit: Rather than fixing this, just make it forward directly to the underlying buffer)

---

This ensures that the buffer is large enough for the specified width, height, bits-per-pixel, and stride.

Also makes the legacy FrameBuffer1 constructor re-use the FrameBuffer make_new to save some code size and hopefully offset this a bit.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by jimmo** [comment]
There are two easy code-size optimisations we could add to this:

1. change the values of the `FRAMEBUF_MVLSB` etc constants such that they encode the bits-per-pixel directly in their value (not sure if this is a breaking change though??).
2. rather than having to re-compute `height_required` for `MONO_VLSB` we could just update the specified height to round it up. Similar to what we already do for stride. I think this actually makes sense because a display driver will be writing this data out to the display anyway.

**Comment by jimmo** [comment]
Another code size win would be to make FrameBuffer's get-buffer just directly return the underlying buffer (i.e. forward to `mp_get_buffer(self->buf_obj)`. But I think it makes sense that it sets the length correctly to what the framebuffer is actually using.

**Comment by jimmo** [comment]
>     1. change the values of the `FRAMEBUF_MVLSB` etc constants such that they encode the bits-per-pixel directly in their value (not sure if this is a breaking change though??).

This might end up adding more code size elsewhere in order to continue to use them as keys for the formats array.

>     2. rather than having to re-compute `height_required` for `MONO_VLSB` we could just update the specified height to round it up. Similar to what we already do for stride. I think this actually makes sense because a display driver will be writing this data out to the display anyway.

If a framebuf is used as a sprite, then it must maintain its original height.

> Another code size win would be to make FrameBuffer's get-buffer just directly return the underlying buffer (i.e. forward to `mp_get_buffer(self->buf_obj)`. But I think it makes sense that it sets the length correctly to what the framebuffer is actually using.

I did this.

File: extmod/modframebuf.c [hunk 1]
```diff
@@ -319,11 +336,8 @@ STATIC void framebuf_args(const mp_obj_t *args_in, mp_int_t *args_out, int n) {
 }
 
 STATIC mp_int_t framebuf_get_buffer(mp_obj_t self_in, mp_buffer_info_t *bufinfo, mp_uint_t flags) {
-    (void)flags;
     mp_obj_framebuf_t *self = MP_OBJ_TO_PTR(self_in);
-    bufinfo->buf = self->buf;
-    bufinfo->len = self->stride * self->height * (self->format == FRAMEBUF_RGB565 ? 2 : 1);
-    bufinfo->typecode = 'B'; // view framebuf as bytes
+    mp_get_buffer_raise(self->buf_obj, bufinfo, flags);
```
Comment (dpgeorge) [inline extmod/modframebuf.c:340]: This should return 1 if it doesn't support the buffer protocol, not raise an exception.  So maybe calling `mp_get_buffer()` is conceptually better here (even though it's never going to raise because the buf is already validated to be a buffer in the FrameBuffer constructor).

Comment (jimmo) [reply extmod/modframebuf.c]: Yep, fixed.

File: tests/extmod/framebuf1.py [hunk 2]
```diff
@@ -106,6 +106,13 @@
...
 
 # test legacy constructor
-fbuf = framebuf.FrameBuffer1(buf, w, h)
-fbuf = framebuf.FrameBuffer1(buf, w, h, w)
+if hasattr(framebuf, "FrameBuffer1"):
+    fbuf = framebuf.FrameBuffer1(buf, w, h)
+    fbuf = framebuf.FrameBuffer1(buf, w, h, w)
 print(framebuf.MVLSB == framebuf.MONO_VLSB)
+
+# test get-buffer (returns subset of the original buffer)
```
Comment (dpgeorge) [inline tests/extmod/framebuf1.py:114]: I think this comment is wrong, it no longer returns a subset.

File: extmod/modframebuf.c [hunk 3]
```diff
@@ -851,28 +864,15 @@ STATIC MP_DEFINE_CONST_OBJ_TYPE(
     );
 #endif
 
-// this factory function is provided for backwards compatibility with old FrameBuffer1 class
+#if !MICROPY_ENABLE_DYNRUNTIME
+// this factory function is provided for backwards compatibility with old
```
Comment (dpgeorge) [inline extmod/modframebuf.c:868]: Capital letter at the start?

File: extmod/modframebuf.c [hunk 4]
```diff
@@ -273,42 +273,59 @@ STATIC void fill_rect(const mp_obj_framebuf_t *fb, int x, int y, int w, int h, u
...
 
-    o->width = mp_obj_get_int(args_in[1]);
-    o->height = mp_obj_get_int(args_in[2]);
-    o->format = mp_obj_get_int(args_in[3]);
-    if (n_args >= 5) {
-        o->stride = mp_obj_get_int(args_in[4]);
-    } else {
-        o->stride = o->width;
+    if (width < 1 || height < 1 || width > 0xffff || height > 0xffff || stride > 0xffff || stride < width) {
+        mp_raise_ValueError(MP_ERROR_TEXT("bounds"));
```
Comment (dpgeorge) [inline extmod/modframebuf.c:282]: Did you try making the error message just NULL?

Comment (jimmo) [reply extmod/modframebuf.c]: -8 bytes (it's not already in the compressed table).

**Comment by dpgeorge** [comment]
Rebased on master to pick up changes from #12679, and merged.
