### PR TITLE
py/scheduler: Allow C scheduler callbacks to re-queue themselves.

### LINKED ISSUE #17246: BLE init failures can cause infinite loop in scheduler
### Port, board and/or hardware

stm32wb55

### MicroPython version

master branch, slightly newer than v1.25

### Reproduction

On a stm32wb55 based board with the rfcore (WS) firmware blob wiped / damaged.
```
from bluetooth import BLE
BLE().active(1)
```
Ends up stuck with `tl_ble_wait_resp: timeout` repeated on the command line every few seconds.

### Expected behaviour

The `tl_ble_wait_resp: timeout` message is expected due to lack of response from the rfcore, however there is a timeout in C so this should only retry a limited number of times (2 seconds worth) before aborting with a Timeout error: https://github.com/micropython/micropython/blob/79abdad9e97f18f45650e1abce64ee51c3372953/extmod/nimble/modbluetooth_nimble.c#L632

### Observed behaviour

Instead, the `tl_ble_wait_resp: timeout` message repeats forever. On my application this cannot be ctrl-c interrupted, it reboots after some time only because we have a WDT running.

### Additional Information

I've debugged the issue down to the scheduler, specifically the C STATIC_NODES section of it:

Image

In this case the C scheduler is used to run `mp_bluetooth_hci_poll()`. Due to timeout trying to communicate with hci a  `ble_hs_reset()` gets run on the nimble os_eventq which starts by resetting the hci transport.
That flows through to mp_bluetooth_hci_uart_init() which itself starts the hci polling...

Image

This re-inserts the hci poll function into head of the c schedule linked list meaing it's ready to be run immediately, forming an infinite loop in `mp_sched_run_pending()`

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Currently if a scheduler callbacks queues a new C scheduled callback, that callback will run in the same schedule pass. This means if a scheduler callback re-queues itself, it can "infinite loop" inside the scheduler.

This change means that any call to `mp_handle_pending()` will only process the callbacks which were queued when `mp_handle_pending()` started running. Therefore any callback which re-queues itself should have that callback handled the next time `mp_handle_pending()` is called.

This is an alternative to #17248 and should remove the need for #17264. Fixes #17246.

This does create potential for some additional callback latency (i.e. if an interrupt fires while a different scheduler callback is running, the interrupt callback is now deferred until the next scheduler run). However the worst-case scheduler latency remains similar (interrupt fires at end of one scheduler pass, has to wait until the next one). I think most MicroPython systems only sparsely call C scheduler callbacks, so this shouldn't be noticeable in most cases.

There is also potential for a misbehaving callback that re-schedules itself continuously to degrade performance of MicroPython (as the callback runs continuously with some allowance for Python code to run), whereas before it would have locked up MicroPython entirely which is more obviously broken.

*This work was funded through GitHub Sponsors.*

### Testing

* I adapted the test case @andrewleech added in #17248 for the new behaviour and resubmitted here, so coverage test now includes C scheduler callbacks (testing the new logic).
* Manually ran the rp2 unit tests on RP2_PICO board. As this is a tickless port I felt it had the most potential for an interrupt timing bug to surface due to this change. All passed.

### Trade-offs and Alternatives

* Possible to manually add anti-recursion checks in callbacks, i.e. approach in #17264, but it can get fiddly quickly.

### CODE REVIEW

**Comment by projectgus** [comment]
@andrewleech Are you able to easily reproduce the issue that #17264 is fixing? Am interested to know if this fixes it OK, I noticed just now that PR links to your commit https://github.com/micropython/micropython/commit/af4a8e9cfc6df2467bb492d4794e377a8d80cb37 which implies the problem is actually with recursive calls to `mp_handle_pending()` itself rather than callbacks re-adding themselves, so that might need a different fix...

**Comment by andrewleech** [comment]
Thanks for this @projectgus yes it's easy to reproduce with a stm32wb55 that's had its rfcore firmware wiped, when trying to start BLE it gets stuck trying to init forever in a loop, the higher level timeout code never runs. 
I'll get a unit set up to test the change.

File: py/scheduler.c [hunk 1]
```diff
@@ -99,6 +100,9 @@ static inline void mp_sched_run_pending(void) {
         MICROPY_END_ATOMIC_SECTION(atomic_state);
         callback(node);
         atomic_state = MICROPY_BEGIN_ATOMIC_SECTION();
+        if (node == original_tail) {
+            break; // Don't execute any callbacks scheduled during this run
+        }
```
Comment (dpgeorge) [inline py/scheduler.c:105]: Can this be rewritten as:
```c
mp_sched_node_t *original_tail = MP_STATE_VM(sched_tail);
while (MP_STATE_VM(sched_head) != original_tail) {
    ...
}
```
?

**Comment by andrewleech** [comment]
Current master:
``` python
MicroPython v1.26.0-preview.148.g49f81d5046 on 2025-05-24; NUCLEO-WB55 with STM32WB55RGV6
Type "help()" for more information.
>>> 
>>> 
>>> from bluetooth import BLE
>>> BLE().active()
False
>>> BLE().active(True)
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout

```
Note: Ctrl-C did not working here, I couldn't break out of the error loop other than hard reset.

With this PR:
``` python
MicroPython v1.26.0-preview.150.g8b14be1c02 on 2025-05-24; NUCLEO-WB55 with STM32WB55RGV6
Type "help()" for more information.
>>> from bluetooth import BLE
>>> BLE().active()
False
>>> BLE().active(True)
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
tl_ble_wait_resp: timeout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 110] ETIMEDOUT
>>> 

```

**Review by andrewleech — APPROVED** [review]

File: py/scheduler.c (hunk 1 above)
Comment (projectgus) [reply py/scheduler.c:105]: No, that way the scheduler always skips the last entry in the list. I think it could be written slightly differently as:

```c
mp_sched_node_t *original_tail = MP_STATE_VM(sched_tail);
if (MP_STATE_VM(sched_head) != NULL) {
    do {
      ..
  } while (MP_STATE_VM(sched_head) != original_tail);
}
```

(Provided the list entries aren't ever modified during the run - apart from appending - which is currently the case.)

This takes the comparison to NULL out of the loop body. Unsure if that'd make much difference in the binary, but I can test it out if you like this way.

Comment (projectgus) [reply py/scheduler.c:105]: (Edited the above as I think can remove a pointer lookup by comparing `original_tail` to `NULL` instead of `MP_STATE_VM(sched_head)`.)

**Comment by projectgus** [comment]
Thanks @andrewleech for confirming this fixes the WB55 issue!

File: py/scheduler.c (hunk 1 above)
Comment (projectgus) [reply py/scheduler.c]: In a local build, code size for rp2 was the same as the current version after I moved the `original_tail` assignment outside of the loop.

**Review by dpgeorge — APPROVED** [review]
Looks good now!
