### PR TITLE
Fixed `str % dict` edge case.

### LINKED ISSUE #11963: `"something" % {}` raises `TypeError: format string didn't convert all arguments`
Granted, this is an edge case. But not unthinkable.
I encountered it in a logging function a-la `logging.Logger`'s `.info(format, *args, **kwargs)` with a string that had no format args.

```
MicroPython v1.20.0 on 2023-04-26; ESP32 module with ESP32

>>> "something" % {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: format string didn't convert all arguments
>>> 
```

Expected behavior:
```
Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> "something" % {}
'something'
>>>
```

### PR DESCRIPTION
**Pull request by udi-barzilai**
Eliminate `TypeError` when fmt string contains no named conversions. This matches CPython behavior.

This should fix #11963

(This replaces PR #11968)

### CODE REVIEW

File: py/objstr.c [hunk 1]
```diff
@@ -1645,6 +1645,11 @@ STATIC mp_obj_t str_modulo_format(mp_obj_t pattern, size_t n_args, const mp_obj_
         }
     }
 
+    if (dict != MP_OBJ_NULL) {
+        // if `dict` exists, then it was the only element in `args` and it was consumed; either positionally, or
+        // as a map of named args, even if none were actually referenced by `pattern`.
+        arg_i = 1;
```
Comment (dpgeorge) [inline py/objstr.c:1651]: If dict is supplied then n_args=1, so it would be simpler to write the below if condition as:
```c
if (dict == MP_OBJ_NULL && arg_i != n_args) {
```

Comment (mcskatkat) [reply py/objstr.c:1651]: > If dict is supplied then n_args=1, so it would be simpler to write the below if condition as:

Right. It is logically the same but I thought the reasoning is better shown by setting `arg_i` to indicate that the dict was consumed, same as through the path where there are references to dict keys in the fmt string.

Note that the (convoluted, IMHO) behavior of CPython *absolutely requires* that `arg_i` be set to 1 (= dict consumed positionally) when performing a successful lookup in the dict... It affects behavior if there are subsequent positional arg references.

Because this check for `arg_i == nargs` is the last thing the function does, there is really no necessity to update `arg_i` "correctly". 

Anyway since efficiency is more important in embedded code and this saves an asm instruction, you're right. I'll make the change.

**Comment by mcskatkat** [comment]
I suspect that the `unix port / coverage_32bit` test that fails does so at random occasionally. I can't see a connection between that thread related test and the code changes in the PR.
This is the second time I've seen this failure happen.

Hopefully I will get heads on the next coin toss after I push another change.

**Review by dpgeorge — APPROVED** [review]
Thanks, this looks good now!

If you'd like to squash and rebase, you can do that now.  Otherwise I will do it during the merge.

**Comment by dpgeorge** [comment]
Thanks for the contribution.
