### PR TITLE
Fix reverse slicing of lists.

### LINKED ISSUE #1711: list slicing issue on reversed slicing
Reversed list slicing doesn't work correctly, if indices are specified.

Micropython:

```
>>> [1,2,3,4,5][:0:-1]
[]
>>> [1,2,3,4,5][:1:-1]
[1]
>>> [1,2,3,4,5][:2:-1]
[2, 1]

>>> [1,2,3,4,5][0::-1]
[5, 4, 3, 2, 1]
>>> [1,2,3,4,5][1::-1]
[5, 4, 3, 2]
>>> [1,2,3,4,5][2::-1]
[5, 4, 3]
```

CPython 3.4:

```
>>> [1,2,3,4,5][:0:-1]
[5, 4, 3, 2]
>>> [1,2,3,4,5][:1:-1]                                                                                        
[5, 4, 3]
>>> [1,2,3,4,5][:2:-1]                                                                                        
[5, 4]

>>> [1,2,3,4,5][0::-1]
[1]
>>> [1,2,3,4,5][1::-1]
[2, 1]
>>> [1,2,3,4,5][2::-1]
[3, 2, 1]
```

### PR DESCRIPTION
**Pull request by utzig**
This fixes the slicing when using reversed lists (negative step). Closes #1711.

### CODE REVIEW

File: py/sequence.c [hunk 1]
```diff
@@ -70,29 +90,31 @@ bool mp_seq_get_fast_slice_indexes(mp_uint_t len, mp_obj_t slice, mp_bound_slice
...
     indexes->start = start;
     indexes->stop = stop;
 
-    if (ostep != mp_const_none && ostep != MP_OBJ_NEW_SMALL_INT(1)) {
-        indexes->step = mp_obj_get_int(ostep);
-        return false;
-    }
-    indexes->step = 1;
-    return true;
+    return (indexes->step == 1) ? true : false;
```
Comment (pfalcon) [inline py/sequence.c]: "?:" here is superfluous, indexes->step == 1 is already boolean expression.

**Comment by pfalcon** [comment]
If possible, please squash changes together, and this looks good to go.

**Comment by pfalcon** [comment]
Merged. Great work, thanks!
