### PR TITLE
top: Common network hostname/country configuration.

### LINKED ISSUE #8906: Can't set hostname in AP mode
**Board**: Raspberry Pico W
**Firmware file name**: rp2-pico-w-20220713-unstable-v1.19.1-129-g5bf376563.uf2

I can't set the "hostname" param with config() function.

This works (without hostname param):
```
import network
wlan = network.WLAN(network.AP_IF)
wlan.config(essid='somessid', key="1234567890")
wlan.active(True)
```

This doesn't work:
```
import network
wlan = network.WLAN(network.AP_IF)
wlan.config(essid='somessid', key="1234567890", hostname="somehostname")
wlan.active(True)
```
and prints this error:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: unknown config param
```

I've tried with "dhcp_hostname" also, same result.

### PR DESCRIPTION
**Pull request by jimmo**
The overall goal is to allow configuration of the hostname on Pico W, but also unify the way networking works across ports. Fixes #8906, #10397

This PR adds `network.hostname()` and `network.country()` to globally set the device hostname (for all interfaces) and country (for radio compliance). For interfaces that previously supported `nic.config(hostname)` this will continue to work, as will `pyb.country()` (and `rp2.country()`).

Additionally configure the default hostname on a per-port and per-board basis. We may want to remove this change if it's considered a breaking change to change the default hostname?

It also updates the stm32 port to use the new cyw43-driver (in the lib/cyw43-driver submodule) and removes the old version from drivers. This relies on https://github.com/georgerobotics/cyw43-driver/pull/58.

Next steps (separate PR):
 - Investigate configuring mDNS more explicitly. See #9058 and #9086 for more history.
 - Implement hostname for other NICs (Nina, Wiznet) and country for all other non-cyw43 wifi (Nina, ESP8266, ESP32).
 - Unify other networking config, in particular the auth and mode constants, and make it possible to write the same code on all ports to manage the WiFi interface. Eventually I'd like to remove the modnetwork customisations used by ESP8266/ESP32 and have them work like the other ports.

### CODE REVIEW

**Comment by jimmo** [comment]
This removes `pyb.country` for boards that don't have networking... Is that going to be a problem?

**Comment by dpgeorge** [comment]
> This removes `pyb.country` for boards that don't have networking... Is that going to be a problem?

It might be... the default `boot.py` has a `pyb.country()` entry regardless of networking support or not.  So a lot of boards are still going to have that line in their `boot.py`.  The idea was that even on a PYBv1.1 you might want to configure the country.

**Comment by jimmo** [comment]
> It might be... the default `boot.py` has a `pyb.country()` entry regardless of networking support or not. So a lot of boards are still going to have that line in their `boot.py`. The idea was that even on a PYBv1.1 you might want to configure the country.

OK. I've added a "no-op" version of pyb.country for boards that don't have networking support so that existing boards with the default boot.py don't break. I've also updated the default boot.py to use network.country and network.hostname instead.

It seems unnecessary to add the whole network module for non-networking boards just to have a .country method that does nothing.

**Comment by jimmo** [comment]
Updated the submodule, including removing the cyw43_resource.o handling in favour of the firmware header files. Note that this breaks Pico W until the next Pico SDK update (at which point I will update this PR).

**Comment by dpgeorge** [comment]
> Note that this breaks Pico W until the next Pico SDK update

See #10764 which does the update to pico-sdk.

**Comment by dpgeorge** [comment]
Please rebase on latest master to get the new pico-sdk (and cyw43-driver).

**Comment by jimmo** [comment]
> Please rebase on latest master to get the new pico-sdk (and cyw43-driver).

Done.

**Comment by dpgeorge** [comment]
This now passes the CI.

I tested BLE and WiFi on PYBD-SF2W and it looks good, but I want to do more tests.

File: extmod/modnetwork.c [hunk 1]
```diff
@@ -89,9 +89,52 @@ STATIC mp_obj_t network_route(void) {
 }
 STATIC MP_DEFINE_CONST_FUN_OBJ_0(network_route_obj, network_route);
 
+
+char mod_network_country_code[2] = "XX";
```
Comment (dpgeorge) [inline extmod/modnetwork.c:94]: this variable definition should go at the top of the file, just before the start of function definitons

File: extmod/modnetwork.c [hunk 2]
```diff
@@ -89,9 +89,52 @@ STATIC mp_obj_t network_route(void) {
...
+    }
+}
+// TODO: Non-static to allow backwards-compatible pyb.country.
+MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_network_country_obj, 0, 1, network_country);
+
+#ifndef MICROPY_PY_NETWORK_DEFAULT_HOSTNAME
+#error "MICROPY_PY_NETWORK_DEFAULT_HOSTNAME must be set in mpconfigport.h or mpconfigboard.h"
+#endif
+
+char mod_network_hostname[MICROPY_PY_NETWORK_MAX_HOSTNAME_LEN] = MICROPY_PY_NETWORK_DEFAULT_HOSTNAME;
```
Comment (dpgeorge) [inline extmod/modnetwork.c:117]: move to top of file

File: extmod/modnetwork.c [hunk 3]
```diff
@@ -89,9 +89,52 @@ STATIC mp_obj_t network_route(void) {
...
+        mod_network_country_code[0] = str[0];
+        mod_network_country_code[1] = str[1];
+        return mp_const_none;
+    }
+}
+// TODO: Non-static to allow backwards-compatible pyb.country.
+MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_network_country_obj, 0, 1, network_country);
+
+#ifndef MICROPY_PY_NETWORK_DEFAULT_HOSTNAME
+#error "MICROPY_PY_NETWORK_DEFAULT_HOSTNAME must be set in mpconfigport.h or mpconfigboard.h"
```
Comment (dpgeorge) [inline extmod/modnetwork.c:114]: how about naming this `MICROPY_PY_NETWORK_HOSTNAME_DEFAULT`?  the point being that it's a configuration of `network.hostname`

File: extmod/modnetwork.c (hunk 2 above)
Comment (dpgeorge) [reply extmod/modnetwork.c:117]: also, as above, this could be named `MICROPY_PY_NETWORK_HOSTNAME_MAX_LEN`

File: extmod/modnetwork.h [hunk 4]
```diff
@@ -106,4 +106,12 @@ void mod_network_deinit(void);
 void mod_network_register_nic(mp_obj_t nic);
 mp_obj_t mod_network_find_nic(const uint8_t *ip);
 
+extern char mod_network_country_code[2];
+
+#ifndef MICROPY_PY_NETWORK_MAX_HOSTNAME_LEN
+#define MICROPY_PY_NETWORK_MAX_HOSTNAME_LEN (16)
+#endif
+
+extern char mod_network_hostname[MICROPY_PY_NETWORK_MAX_HOSTNAME_LEN];
```
Comment (dpgeorge) [inline extmod/modnetwork.h:117]: same as in the .c file, these should go before function definitions

File: extmod/network_cyw43.c [hunk 5]
```diff
@@ -119,14 +120,21 @@ STATIC mp_obj_t network_cyw43_deinit(mp_obj_t self_in) {
...
+#endif
+
 STATIC mp_obj_t network_cyw43_active(size_t n_args, const mp_obj_t *args) {
     network_cyw43_obj_t *self = MP_OBJ_TO_PTR(args[0]);
     if (n_args == 1) {
         return mp_obj_new_bool(cyw43_tcpip_link_status(self->cyw, self->itf));
     } else {
         #if MICROPY_PY_NETWORK_CYW43_USE_LIB_DRIVER
-        cyw43_wifi_set_up(self->cyw, self->itf, mp_obj_is_true(args[1]), MICROPY_CYW43_COUNTRY);
+        uint32_t country = CYW43_COUNTRY(mod_network_country_code[0] || 'X', mod_network_country_code[1] || 'X', 0);
```
Comment (dpgeorge) [inline extmod/network_cyw43.c:124]: is it necessary to do the `|| 'X'`?  isn't it already checked that the value set by the user is a string of length 2?

File: ports/rp2/boards/W5100S_EVB_PICO/mpconfigboard.h [hunk 6]
```diff
@@ -1,8 +1,9 @@
 // Board config for Wiznet W5100S-EVB-Pico.
 
 // Board and hardware specific configuration
-#define MICROPY_HW_BOARD_NAME             "W5100S-EVB-Pico"
-#define MICROPY_HW_FLASH_STORAGE_BYTES    (1408 * 1024)
+#define MICROPY_HW_BOARD_NAME               "W5100S-EVB-Pico"
+#define MICROPY_PY_NETWORK_DEFAULT_HOSTNAME "W5100S-EVB"
```
Comment (dpgeorge) [inline ports/rp2/boards/W5100S_EVB_PICO/mpconfigboard.h:5]: I usually try not to mix HW and PY config options.  Maybe this can go down just below `MICROPY_PY_NETWORK`?

**Comment by jimmo** [comment]
Addressed all comments.

**Comment by dpgeorge** [comment]
Thank you, this looks good now.  I rebased and updated some of the commit messages (minor changes) and force pushed to this PR branch.

**Comment by robert-hh** [comment]
Thanks @jimmo. That was quite a piece of work, and needed.

**Comment by DataMinded** [comment]
can we add a few DHCP options in the made discover and offer requests ?
If I capture an raspberry pi 3 with hostname set  DHCP discover and request packages ,I can see it includes a few more parameters, and options in the 55- Parameter Request list .
The RPI is accessable by other devices within the same network by hostname.local  . this is not true for the current micropython dhcp handshake ,  can we add these options to it ??   Unsure where to look to try it myself

Check images below , left is RPI , right is Pico W
image


image



image
I would assume these changes would make the pico W accessable by hostname in local networks
