### PR TITLE
rp2/rp2_pio: Fix PIO support for pin wrapping and RP2350B upper-bank pins.

### LINKED ISSUE #16199: PIO does not work on RP2350B with GPIO pin >=32
### Port, board and/or hardware

rp2 port with RP2350B

### MicroPython version

v1.24.0-preview.461.gb8227a3f7.dirty

### Reproduction

Connect a quadrature encoder to any pair of GPIO pins. Then create an instance of this class, which implements a quadrature decoder using PIO: https://github.com/Open-STEM/XRP_MicroPython/blob/main/XRPLib/encoder.py

Then run the following while rotating the encoder:

```
pinA = 0
pinB = 1

myEncoder = Encoder(0, pinA, pinB)

while True:
    print(myEncoder.get_position_counts())
    time.sleep(0.1)
```

### Expected behaviour

A PIO encoder should work on any pair of pins, and the printed output should change as the encoder rotates.

### Observed behaviour

A PIO encoder only works if `pinA` and `pinB` are <32. If they're >=32, the printed output is fixed at 0.

### Additional Information

I'm not super familiar with MicroPython, but this appears to be where the state machine is created:

https://github.com/micropython/micropython/blob/5dfbd4371480c175e6f54e57e4e5eb5d579cbd00/ports/rp2/rp2_pio.c#L726-L743

Which eventually calls [this Pico SDK function](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/hardware_pio/include/hardware/pio.h#L381-L383):

https://github.com/micropython/micropython/blob/5dfbd4371480c175e6f54e57e4e5eb5d579cbd00/ports/rp2/rp2_pio.c#L666-L669

Not sure whether the root problem is with MicroPython or the Pico SDK, but I suspect it may be related to https://github.com/raspberrypi/pico-sdk/issues/2030 TLDR; need to set `pio->gpiobase` to 16 if the pin is >=32.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by AJMansfield**
### Summary
The existing public pico-sdk API methods for `pio_sm_set_pins_with_mask`/`pio_sm_set_pindirs_with_mask`, including the 64-bit variants, do not allow PIO "pin wrapping", i.e. using `[30, 31, 0, 1]` or `[46, 47, 16, 17]` as contiguous pin ranges for a PIO program, despite the documented support for this in the underlying hardware.

This patch exposes the internal method that the existing 32- and 64-bit versions of these functions call to in order to skip the way the wrappers "helpfully" perform truncated bit-shifts on their arguments, and uses it to also resolve the outstanding issue with using upper-bank RP2350B pins for PIO.

Resolves: #16199
Closes: #16985

### Testing
This still needs to be tested with real RP2350B hardware, not just the more common RP2350A --- as this is a key area where these two chips are different. At the moment I do not have suitable hardware to test on.

### CODE REVIEW

**Comment by AJMansfield** [comment]
@Gadgetoid @sfe-SparkFro @maholli Are any of you able to test if this resolves the issue?

**Comment by sfe-SparkFro** [comment]
Thanks!

Did `rp2.PIO.gpio_base` get removed at some point? [My previous test code](https://github.com/micropython/micropython/issues/16199#issuecomment-3255488965) leveraged that. Will see about making a new test tomorrow, if no one else has by then.

**Comment by AJMansfield** [comment]
> Did `rp2.PIO.gpio_base` get removed at some point? [My previous test code](https://github.com/micropython/micropython/issues/16199#issuecomment-3255488965) leveraged that. Will see about making a new test tomorrow, if no one else has by then.

It should be just as it was, only with upper-range GPIO pins now fully functional.

**Comment by sfe-SparkFro** [comment]
Doh, my mistake! Was building for the Pico 2, which is not the RP2350*B*, so `gpio_base` gets `#ifdef`'d out :facepalm:

Can confirm that this works with the RP2350B!

**Comment by sfe-SparkFro** [comment]
@dpgeorge Can this please be considered for v1.27? Or even #16985. We at SparkFun have an upcoming product that really needs #16199 to be resolved. We can of course include it in a release in our fork, though we strive to have minimal differences with our fork where possible. At least some indication of when #16199 will be resolved would be wonderful, thank you!

File: ports/rp2/sdk_inc/hardware/pio.h [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#include_next "hardware/pio.h"
```
Comment (dpgeorge) [inline ports/rp2/sdk_inc/hardware/pio.h]: Instead of using `include_next` which (as I understand) is a gcc extension, how about just naming this file `sdk_inc/pio_internal.h` and including that directly in `rp2_pio.c`?  That also eliminates the need to add `sdk_inc` to the include path in `CMakeLists.txt`.

File: ports/rp2/sdk_inc/hardware/pio.h [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+#ifndef MP_HARDWARE_PIO_H
+#define MP_HARDWARE_PIO_H
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+#if PICO_PIO_USE_GPIO_BASE
+void pio_sm_set_pins_internal(PIO pio, uint sm, uint32_t pins);
```
Comment (dpgeorge) [inline ports/rp2/sdk_inc/hardware/pio.h]: This function isn't used by us, so does it need to be exposed here?

File: ports/rp2/rp2_pio.c [hunk 3]
```diff
@@ -270,13 +270,18 @@ static void asm_pio_get_pins(PIO pio, const char *type, mp_obj_t prog_pins, mp_o
...
+}
 static void asm_pio_init_gpio(PIO pio, uint32_t sm, asm_pio_config_t *config) {
-    uint32_t pinmask = ((1 << config->count) - 1) << (config->base - pio_get_gpio_base(pio));
-    pio_sm_set_pins_with_mask(pio, sm, config->pinvals << (config->base - pio_get_gpio_base(pio)), pinmask);
-    pio_sm_set_pindirs_with_mask(pio, sm, config->pindirs << (config->base - pio_get_gpio_base(pio)), pinmask);
-    for (size_t i = 0; i < config->count; ++i) {
-        gpio_set_function(config->base + i, GPIO_FUNC_PIO0 + pio_get_index(pio));
+    uint32_t gpio_base = pio_get_gpio_base(pio);
+    uint32_t pinmask = rotl32a(~(-1 << config->count), config->base - gpio_base);
+    pio_sm_set_pins_with_mask_internal(pio, sm, rotl32a(config->pinvals, config->base - gpio_base), pinmask);
```
Comment (dpgeorge) [inline ports/rp2/rp2_pio.c]: Is it possible to call `pio_sm_set_pins_with_mask64()` instead of the internal one?  Eg:
```c
pio_sm_set_pins_with_mask64(pio, sm, rotl32a(config->pinvals, config->base - gpio_base) << gpio_base, pinmask << gpio_base);
```
From my reading of the pico-sdk code, that should be equivalent to directly calling the internal function, right?

File: ports/rp2/rp2_pio.c [hunk 4]
```diff
@@ -270,13 +270,18 @@ static void asm_pio_get_pins(PIO pio, const char *type, mp_obj_t prog_pins, mp_o
...
+    pio_sm_set_pindirs_with_mask_internal(pio, sm, rotl32a(config->pindirs, config->base - gpio_base), pinmask);
```
Comment (dpgeorge) [inline ports/rp2/rp2_pio.c]: Same comment as above, can we call `pio_sm_set_pindirs_with_mask64()`?

**Review by dpgeorge — COMMENTED** [review]
Thanks @AJMansfield for this, it's definitely good to support wrapping.

Some comments above, but overall this looks like a good approach.

File: ports/rp2/rp2_pio.c (hunk 3 above)
Comment (AJMansfield) [reply ports/rp2/rp2_pio.c]: The key difference is this part:
```C
#if PICO_PIO_USE_GPIO_BASE
    pin_values >>= pio_get_gpio_base(pio);
    pin_mask >>= pio_get_gpio_base(pio);
#endif
```
I can push a variant that works around this with an extra set of bit-shifts and the mask64 methods when this is applicable, though --- slightly less efficient on code size, but it's still nice to drop the dependency on a non-public part of the API.

File: ports/rp2/sdk_inc/hardware/pio.h (hunk 1 above)
Comment (AJMansfield) [reply ports/rp2/sdk_inc/hardware/pio.h]: AFAIK pico-sdk doesn't support MSVC anyway, so using features not available in MSVC isn't inappropriate for code this hyperspecific to pico-sdk.
But you're right, oher consumers of `hardware/pio.h` don't actually want those internal methods exposed anyway. Mostly, this was just a pattern I've used before for tweaking the sdk to generate MicroPython exceptions from its fault handler.

**Comment by AJMansfield** [comment]
@sfe-SparkFro I've pushed a new revision that should in theory behave identically, but I still lack means to test it directly. Could you test 198970c and report whether this still resolves the problem?

**Comment by dpgeorge** [comment]
Thanks @AJMansfield for updating the PR.  It looks really good now, good not to depend on internal APIs.

**Review by dpgeorge — APPROVED** [review]
I tested this on a PIMORONI_PICO_PLUS2_RP2350 (thanks @Gadgetoid !) using the script from https://github.com/micropython/micropython/issues/16199#issuecomment-3255488965 modified to test with `out_base=Pin(20)` and `out_base=Pin(36)`.  Without the fix in this PR it does not work when using `gpio_base(16)` (the pin doesn't toggle).  But with this PR it does work.
