### PR TITLE
core,rp2,esp8266,windows, unix: Add new cross-port functions for event waiting and handling.

### LINKED ISSUE #12925: rp2: Timeout regression in select/poll, cyw43, others
Prior to commit b41055a5 (PR #12837), this sequence returns immediately (1ms delay):

```
>>> import select
>>> select.poll().poll(1)
[]
```

Since that commit, it may hang indefinitely as extmod/modselect.c calls `MICROPY_EVENT_POLL_HOOK` while polling for a ready fd or for the timeout to be reached.

More generally, select/poll timeout may not be reached in a quiet rp2 system without a lot of interrupts.

The same problem will probably be seen in `network_cyw43.c:226` (connect timeout), lwip recvfrom (recv timeout), NimBLE ble stack timeout... basically anywhere that calls `MICROPY_EVENT_POLL_HOOK` in a tight loop which also checks a timeout condition.

Similar bug to #12912, but harder to fix.

### PR DESCRIPTION
**Pull request by projectgus**
This PR fixes #12925, which is a regression on rp2 introduced when rp2 became "tickless" in #12837.

It implements one of the [suggestions from the linked Issue](https://github.com/micropython/micropython/issues/12925#issuecomment-1803038430): to add new functions for "wait for event" and "handle events". The new functions are port-agnostic:

* `mp_event_handle_nowait()` - Handle any pending MicroPython events without waiting for an interrupt or event.
* `mp_event_wait_indefinite()` - Handle any pending MicroPython events and then suspend execution until the next interrupt or event. This function is deliberately named to attract attention when developers use it, as on tickless ports it will cause issues if the developer expects it to return without a corresponding interrupt having occurred.
* `mp_event_wait_ms(mp_uint_t timeout_ms)` - Handle any pending MicroPython events and then suspend execution until the next interrupt or event, or until timeout_ms milliseconds have elapsed.

Each port only needs to provide a `MICROPY_INTERNAL_WFE(OPTIONAL_TIMEOUT)` macro to implement the "wait for event" logic. More port-specific macros may be needed when adding other ports.

These functions are intended to eventually replace `MICROPY_EVENT_POLL_HOOK` and `MICROPY_EVENT_POLL_HOOK_FAST`, although on all ports except rp2 they are currently implemented using these macros.

This PR switches over `extmod`, `rp2` port and the built-in drivers supported by `rp2` to use the new functions, fixing the issue of indefinite sleep under some conditions.

It also switches over `esp8266`, to avoid problems where `i2c.scan()` doesn't call `ets_event_poll()` and can trigger a WDT.

Finally it switches over Windows, as this was necessary to get the same sleep behaviour with the new functions, and unix  so that the coverage tests pass on the new functions.

`rp2` port also enables [SEVONPEND](https://developer.arm.com/documentation/dui0497/a/cortex-m0-peripherals/system-control-block/system-control-register) to ensure `SEV` bit is set on each interrupt, removing potential race conditions between the interrupt and the main thread checking a hardware condition. It may be possible to make this more fine-grained in future by manually calling `SEV` from individual ISRs, but this approach ensures the firmware can't become stuck if a `SEV` is missing.

*This work was funded through GitHub Sponsors.*

### CODE REVIEW

**Comment by projectgus** [comment]
Hmm, so the challenge is making these functions instead of macros is ports with threading.

A lot of the ports with threading call `MP_THREAD_GIL_EXIT()` & `MP_THREAD_GIL_ENTER()` as part of their wait for event hook. These macros are defined in `py/mpthread.h` and they depend on some other headers as well.

This creates a layering violation with `mphal.h` as it's a pretty low level header. The layering violation doesn't matter for macro expansion, provided all of the relevant parts have been included when the macro expands.

Options would seem to be:

1. Make these back into macros.
2. Put these functions somewhere else, a new header like `py/event.h` or perhaps `py/runtime.h` (which contains the closest related functions, from what I can see.)

A version of the second option seems better from the point of view of having headers that "include what they use" and layer nicely, but the first option will be quick and easy...

**Comment by projectgus** [comment]
Oh, I thought of a third option: Convert `mp_wait_for_event_indefinite()` and `mp_wait_for_event(mp_uint_t timeout_ms)` to normal functions instead of inline. Then they can include whatever they need, and there will be a small code size win.

(Unlike the "nowait" version, these generally get called in places where I don't expect the overhead of one more function call will be very noticeable.)

File: py/mphal.h [hunk 1]
```diff
@@ -26,7 +26,9 @@
 #ifndef MICROPY_INCLUDED_PY_MPHAL_H
 #define MICROPY_INCLUDED_PY_MPHAL_H
 
+#include <stddef.h>
 #include <stdint.h>
+#include <stdbool.h>
```
Comment (dpgeorge) [inline py/mphal.h:31]: Do these new includes need to be added?

File: py/runtime.h [hunk 2]
```diff
@@ -26,6 +26,7 @@
 #ifndef MICROPY_INCLUDED_PY_RUNTIME_H
 #define MICROPY_INCLUDED_PY_RUNTIME_H
 
+#include "py/mphal.h"
```
Comment (dpgeorge) [inline py/runtime.h:29]: This breaks the example/natmod builds... I think just remove it from here.  This header should only be included from .c files.

File: ports/rp2/cyw43_configport.h [hunk 3]
```diff
@@ -119,6 +119,6 @@ static inline void cyw43_delay_ms(uint32_t ms) {
     mp_hal_delay_ms(ms);
 }
 
-#define CYW43_EVENT_POLL_HOOK MICROPY_EVENT_POLL_HOOK_FAST
+#define CYW43_EVENT_POLL_HOOK mp_event_handle_nowait()
```
Comment (dpgeorge) [inline ports/rp2/cyw43_configport.h:122]: this file now needs to include runtime.h, to get this function defn

**Comment by dpgeorge** [comment]
I've tested this on a Pico and Pico W and they both now pass all the asyncio tests (again).  Also networking and BLE works on Pico W.

File: py/runtime.h [hunk 4]
```diff
@@ -109,6 +110,46 @@ bool mp_sched_schedule(mp_obj_t function, mp_obj_t arg);
 bool mp_sched_schedule_node(mp_sched_node_t *node, mp_sched_callback_t callback);
 #endif
 
+// Handles any pending MicroPython events without waiting for an interrupt or
+// event.
+STATIC MP_ALWAYSINLINE inline void mp_event_handle_nowait(void) {
```
Comment (dpgeorge) [inline py/runtime.h:115]: When using static-inline the static must always be there, so STATIC should be static.

Write this either as:
```
MP_ALWAYSINLINE static inline ...
```
or:
```
static inline MP_ALWAYSINLINE ...
```

File: py/runtime.h [hunk 5]
```diff
@@ -109,6 +110,46 @@ bool mp_sched_schedule(mp_obj_t function, mp_obj_t arg);
...
+    #else
+    mp_handle_pending(true);
+    #endif
+}
+
+// Handles any pending MicroPython events and then suspends execution until the
+// next interrupt or event.
+//
+// Note: on "tickless" ports this can suspend execution for a long time,
+// don't call unless you know an interrupt is coming to continue execution.
```
Comment (dpgeorge) [inline py/runtime.h:128]: Maybe add "and may also return early".

File: py/runtime.h [hunk 6]
```diff
@@ -109,6 +110,46 @@ bool mp_sched_schedule(mp_obj_t function, mp_obj_t arg);
...
+    #else
+    mp_event_handle_nowait();
+    MICROPY_INTERNAL_WFE(-1);
+    #endif
+}
+
+// Handle any pending MicroPython events and then suspends execution until the
+// next interrupt or event, or until timeout_ms milliseconds have elapsed.
+//
+// This function will often return early.
```
Comment (dpgeorge) [inline py/runtime.h:142]: Maybe phrase it as "may return early".

File: ports/windows/mpconfigport.h [hunk 7]
```diff
@@ -229,12 +229,9 @@ typedef long mp_off_t;
 #if MICROPY_ENABLE_SCHEDULER
 // Use 1mSec sleep to make sure there is effectively a wait period:
 // something like usleep(500) truncates and ends up calling Sleep(0).
-#define MICROPY_EVENT_POLL_HOOK \
-    do { \
-        extern void mp_handle_pending(bool); \
-        mp_handle_pending(true); \
-        msec_sleep(1.0); \
-    } while (0);
+#define MICROPY_INTERNAL_WFE(TIMEOUT_MS) msec_sleep(MIN(1.0, (double)(TIMEOUT_MS)))
```
Comment (dpgeorge) [inline ports/windows/mpconfigport.h:232]: What happens when TIMEOUT_MS is -1?

File: ports/rp2/mpconfigport.h [hunk 8]
```diff
@@ -249,17 +249,16 @@ extern const struct _mp_obj_type_t mod_network_nic_type_wiznet5k;
...
-        extern void mp_handle_pending(bool); \
-        mp_handle_pending(true); \
-    } while (0)
-
-#define MICROPY_EVENT_POLL_HOOK \
-    do { \
-        MICROPY_EVENT_POLL_HOOK_FAST; \
-        __wfe(); \
-    } while (0);
+// Port level Wait for Event macro
```
Comment (dpgeorge) [inline ports/rp2/mpconfigport.h:252]: "Wait-For-Event"

File: ports/rp2/mpconfigport.h [hunk 9]
```diff
@@ -249,17 +249,16 @@ extern const struct _mp_obj_type_t mod_network_nic_type_wiznet5k;
...
+//
+// Do not use this macro directly, call mp_event_wait_indefinite() or mp_event_wait_ms(timeout)
+#define MICROPY_INTERNAL_WFE(TIMEOUT_MS) do { \
+        if ((TIMEOUT_MS) < 0) { \
+            __wfe(); \
+        } else { \
+            best_effort_wfe_or_timeout(make_timeout_time_ms(TIMEOUT_MS)); \
+        } \
+} while (0)
```
Comment (dpgeorge) [inline ports/rp2/mpconfigport.h:261]: please indent this last line by 4 spaces

File: ports/esp8266/esp_mphal.h [hunk 10]
```diff
@@ -24,6 +24,9 @@
  * THE SOFTWARE.
  */
 
+#ifndef _ESP8266_ESP_MPHAL_H
+#define _ESP8266_ESP_MPHAL_H
```
Comment (dpgeorge) [inline ports/esp8266/esp_mphal.h:28]: please use `MICROPY_INCLUDED_ESP8266_ESP_MPHAL_H`

**Comment by dpgeorge** [comment]
I think esp8266 needs to be updated to use the new scheme, because it does things differently to the other ports:
```
#define MICROPY_EVENT_POLL_HOOK {ets_event_poll();}
```
In particular the `i2c.scan()` may cause a watchdog timeout if there are no pull-up resistors on the bus.

File: py/runtime.h [hunk 11]
```diff
@@ -109,6 +110,46 @@ bool mp_sched_schedule(mp_obj_t function, mp_obj_t arg);
...
 #endif
 
+// Handles any pending MicroPython events without waiting for an interrupt or
+// event.
+STATIC MP_ALWAYSINLINE inline void mp_event_handle_nowait(void) {
+    #if defined(MICROPY_EVENT_POLL_HOOK_FAST) && !MICROPY_PREVIEW_VERSION_2
+    // For ports still using the old macros
+    MICROPY_EVENT_POLL_HOOK_FAST
+    #else
+    mp_handle_pending(true);
```
Comment (dpgeorge) [inline py/runtime.h:120]: This is not general enough.  Some ports like esp8266 must do work in addition to `mp_handle_pending()`.  So we need a way to hook into this function with a macro.

I guess for now we could use `MICROPY_EVENT_POLL_HOOK_FAST` for this, but eventually we will need a way to hook.

File: py/runtime.h (hunk 4 above)
Comment (projectgus) [reply py/runtime.h:115]: Oh, I wondered why MicroPython had this `STATIC` macro. Is the idea that sometimes you want to build with more visible symbols?

File: ports/windows/mpconfigport.h (hunk 7 above)
Comment (projectgus) [reply ports/windows/mpconfigport.h:232]: Derp this should be MAX so it always sleeps at least 1ms, good catch.

File: py/runtime.h (hunk 4 above)
Comment (projectgus) [reply py/runtime.h:115]: There's even a comment that explains it! I should have looked.

File: py/runtime.h (hunk 2 above)
Comment (projectgus) [reply py/runtime.h]: This is tricky. Without a definition of `MICROPY_INTERNAL_WFE`, including `runtime.h` will fail (the difference between macros and inline functions is they force you to structure your headers with a more layered "include what you use"!)

Conceptually these "event" functions are a bit different, in as much as runtime.h is "pure Python runtime", mphal.h is "hardware abstractions", and then event functions are a bridge between the two.

I've updated this PR to put them into a new `py/event.h` header, which solves these kind of conflicts (and allows removing all the messing about with esp8266 headers, too.)

Let me know what you think.

File: py/runtime.h (hunk 4 above)
Comment (projectgus) [reply py/runtime.h]: Resolved (in py/event.h now)

File: py/runtime.h (hunk 5 above)
Comment (projectgus) [reply py/runtime.h]: Reworded both these comments to explicitly explain that it's the tick macro that can cause frequent wakeups.

File: ports/rp2/mpconfigport.h (hunk 9 above)
Comment (projectgus) [reply ports/rp2/mpconfigport.h:262]: Each time I change this, uncrustify (in pre-commit) is changing it back...

File: ports/esp8266/esp_mphal.h (hunk 10 above)
Comment (projectgus) [reply ports/esp8266/esp_mphal.h]: Dropped this commit entirely, but I'll submit this as it's own small PR

Comment (projectgus) [reply ports/esp8266/esp_mphal.h]: Over here now: https://github.com/micropython/micropython/pull/13147

File: py/runtime.h (hunk 11 above)
Comment (projectgus) [reply py/runtime.h]: > In the specific case of MICROPY_EVENT_POLL_HOOK_FAST and mp_event_handle_no_wait(), esp8266 port doesn't define this hook at the moment so I think it will keep working much the same?

Ah, I'm with you now that the i2c scan specifically failed over to the "slow" hook if the fast hook wasn't defined.

OK, will check all the ports for this behaviour.

Comment (projectgus) [reply py/runtime.h]: Updated esp8266 with a new hook `MICROPY_INTERNAL_EVENT_HOOK` and verified i2c.scan() completes. Do you know if any other ports relied on that fallback logic in i2c? It looks like probably not.

Compared to before, there is a small behaviour change - esp8266 port will call `ets_event_poll()` anywhere else that `mp_event_handle_nowait()` is called. I think this is only modselect.c though, and it seems like a good idea to be processing wifi events in that instance.

File: py/mphal.h (hunk 1 above)
Comment (projectgus) [reply py/mphal.h]: No, this was a leftover. Thanks!

File: py/runtime.h (hunk 4 above)
Comment (dpgeorge) [reply py/runtime.h]: > Is the idea that sometimes you want to build with more visible symbols?

Yes, exactly.  Although I suspect there are better ways to do that with compiler/linker flags.  So I'd prefer to eventually move away from using our `STATIC` macro.

File: py/runtime.h (hunk 2 above)
Comment (dpgeorge) [reply py/runtime.h]: I'm pretty sure I tried just removing this include and the build worked.... but maybe I didn't test enough.

How about putting these inline functions in `py/mphal.h`?  As you say, they are half hardware abstraction functions.

File: py/runtime.h (hunk 11 above)
Comment (dpgeorge) [reply py/runtime.h]: > Ah, I'm with you now that the i2c scan specifically failed over to the "slow" hook if the fast hook wasn't defined.

Indeed.  The existing behaviour is quite subtle, actually too subtle.  I'm pretty sure only esp8266 relied on it.



> Compared to before, there is a small behaviour change - esp8266 port will call `ets_event_poll()` anywhere else that `mp_event_handle_nowait()` is called. I think this is only modselect.c though, and it seems like a good idea to be processing wifi events in that instance.

That sounds like a good improvement.

**Comment by dpgeorge** [comment]
There's a problem with the AppVeyor CI:
```
c:\projects\micropython\py\event.h(34): warning C4141: 'inline': used more than once (compiling source file C:\projects\micropython\extmod\modselect.c) [C:\projects\micropython\ports\windows\micropython.vcxproj]
         c:\projects\micropython\py\event.h(54): warning C4141: 'inline': used more than once (compiling source file C:\projects\micropython\extmod\modselect.c) [C:\projects\micropython\ports\windows\micropython.vcxproj]
         c:\projects\micropython\py\event.h(68): warning C4141: 'inline': used more than once (compiling source file C:\projects\micropython\extmod\modselect.c) [C:\projects\micropython\ports\windows\micropython.vcxproj]
```

File: py/runtime.h (hunk 2 above)
Comment (dpgeorge) [reply py/runtime.h]: > How about putting these inline functions in `py/mphal.h`? As you say, they are half hardware abstraction functions.

Hmm, maybe that's a bad idea, because then `py/mphal.h` will need to include `py/runtime.h`, which is no good.

Comment (projectgus) [reply py/runtime.h]: Yeah, that's it. My very first version of this added the inlines to`mphal.h` and ran into that problem.

I think conceptually:

* `mphal.h` is "lower" and relates to the hardware.
* `runtime.h` is "higher" and relates to the pure Python layer.
* `event.h` is "in between" the two.

File: ports/esp8266/machine_uart.c [hunk 12]
```diff
@@ -300,7 +301,7 @@ STATIC mp_uint_t mp_machine_uart_ioctl(mp_obj_t self_in, mp_uint_t request, uint
             if (mp_machine_uart_txdone(self)) {
                 return 0;
             }
-            MICROPY_EVENT_POLL_HOOK
+            mp_event_wait_indefinite();
```
Comment (dpgeorge) [inline ports/esp8266/machine_uart.c:304]: This should be `mp_event_wait_ms(1)`, since the loop checks for a timeout.

File: ports/esp8266/mpconfigport.h [hunk 13]
```diff
@@ -116,7 +116,11 @@
 #define MICROPY_FATFS_LFN_CODE_PAGE    437 /* 1=SFN/ANSI 437=LFN/U.S.(OEM) */
 #define MICROPY_ESP8266_APA102         (1)
 
-#define MICROPY_EVENT_POLL_HOOK {ets_event_poll();}
+// No blocking wait-for-event on ESP8266, only non-blocking poll of the OS event
+// loop
+#define MICROPY_INTERNAL_WFE(TIMEOUT_MS)
+#define MICROPY_INTERNAL_EVENT_HOOK ets_event_poll()
```
Comment (dpgeorge) [inline ports/esp8266/mpconfigport.h:122]: The `ets_event_poll()` function is implemented as:
```c
void ets_event_poll(void) {
    ets_loop_iter();
    mp_handle_pending(true);
}
```
It already calls `mp_handle_pending(true)`, so now will call it twice in `mp_event_xxx()` functions.

I suggest changing this macro to call `ets_loop_iter()` directly, remove `ets_event_poll()`, and for the small number of uses of `ets_event_poll()` change them to `mp_event_handle_nowait()`.

File: ports/esp8266/machine_uart.c (hunk 12 above)
Comment (projectgus) [reply ports/esp8266/machine_uart.c:304]: Oops, good catch! (I think they're equivalent on this port, but good to use the correct function anyhow.)

File: py/event.h [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+ */
+#ifndef MICROPY_INCLUDED_PY_EVENT_H
+#define MICROPY_INCLUDED_PY_EVENT_H
+
+#include "py/mphal.h"
+#include "py/runtime.h"
+
+// Handles any pending MicroPython events without waiting for an interrupt or
+// event
+static inline MP_ALWAYSINLINE void mp_event_handle_nowait(void) {
```
[the remark this answers is not in the document]
Comment (projectgus) [reply py/event.h]: Good point, the compiler can be a pretty good judge of these.

(The `mp_event_wait_` ones could even arguably be made into regular functions I think.)

**Comment by projectgus** [comment]
@dpgeorge Coverage is still failing. I think because the only code which calls `mp_event_wait_ms()` on the unix port is `mp_hal_delay_ms`. On unix+float, `time.sleep()` is implemented by calling `sleep_select()`.

It looks like `select()` has been used for sleep with floating point arguments for a long time, since f7662645821d4528f0e36a51ed8d41749748230e and refined in 0bb57bf5bf1c9822abca524aabd00fe9b861d10d.

It seems like it might be reasonable to refactor this to call `mp_hal_delay_ms()` in all cases, though? It'll use a modicum more CPU time, but not a lot.

(The other option might be to implement `MICROPY_INTERNAL_WFE` on unix by calling select, as EINTR causes select to return early, but that seems a lot fiddlier.)

**Comment by dpgeorge** [comment]
> I think because the only code which calls `mp_event_wait_ms()` on the unix port is `mp_hal_delay_ms`. On unix+float, `time.sleep()` is implemented by calling `sleep_select()` not `mp_hal_delay_ms()`.

OK, that's a bit tricky.

How about this then:
```diff
--- a/ports/unix/coverage.c
+++ b/ports/unix/coverage.c
@@ -578,9 +578,9 @@ STATIC mp_obj_t extra_coverage(void) {
         mp_sched_unlock();
         mp_printf(&mp_plat_print, "unlocked\n");
 
-        // drain pending callbacks
+        // drain pending callbacks (and test mp_event_wait_ms())
         while (mp_sched_num_pending()) {
-            mp_handle_pending(true);
+            mp_event_wait_ms(1);
         }
 
         // setting the keyboard interrupt and raising it during mp_handle_pending
```

**Comment by dpgeorge** [comment]
> Oh, I thought of a third option: Convert `mp_wait_for_event_indefinite()` and `mp_wait_for_event(mp_uint_t timeout_ms)` to normal functions instead of inline. Then they can include whatever they need, and there will be a small code size win.

I've changed it so all three of these event functions are normal functions (not inline).

This saves code size, and makes the abstraction a bit stronger.  These functions really don't need to be inline.  The original macros were because that was a bit of a hack that just allowed a port to insert arbitrary code for the polling.  But now that it has been formalised in this PR these event functions are better not inlined.  If they are inline then the more they are used the more code size will grow, and we want to be able to use them on all ports, even ones that are space constrained.

I checked all uses of these event functions and none of them are critical that they warrant (or need, eg to be in IRAM) an inline function.  Better to spend the bytes elsewhere to improve performance.  It also means we don't need a new `py/event.h` header file.

File: py/event.h (hunk 14 above)
[the remark this answers is not in the document]
Comment (dpgeorge) [reply py/event.h]: I've maid them all into functions.

File: ports/windows/mpconfigport.h [hunk 15]
```diff
@@ -227,14 +227,11 @@ typedef long mp_off_t;
...
 // something like usleep(500) truncates and ends up calling Sleep(0).
-#define MICROPY_EVENT_POLL_HOOK \
-    do { \
-        extern void mp_handle_pending(bool); \
-        mp_handle_pending(true); \
-        msec_sleep(1.0); \
-    } while (0);
+#define MICROPY_INTERNAL_WFE(TIMEOUT_MS) msec_sleep(MAX(1.0, (double)(TIMEOUT_MS)))
+#else
+#define MICROPY_INTERNAL_WFE(TIMEOUT_MS) /* No-op */
```
[the remark this answers is not in the document]
Comment (stinos) [reply ports/windows/mpconfigport.h:234]: Not completely sure what MICROPY_INTERNAL_WFE is supposed to do, but scheduler.c has `MICROPY_INTERNAL_WFE(-1)` so that does not seem to work as intended?

[the remark this answers is not in the document]
Comment (dpgeorge) [reply ports/windows/mpconfigport.h:234]: MICROPY_INTERNAL_WFE is "wait for event".  But it can be conservative and return immediately, but in that case it'll use more power/CPU.

If the argument is -1 it means "wait indefinitely for the next event".  Here that would just sleep 1ms.

When MICROPY_ENABLE_SCHEDULER is disabled, I don't think this macro is ever used, so doesn't need to do anything in that case.
