### PR TITLE
webassembly/objpyproxy: Avoid throwing on implicit symbols access.

### LINKED ISSUE #17657: webassembly: getting JS symbols implicitly also throws errors
### Port, board and/or hardware

webassembly

### MicroPython version

MicroPython webassembly latest from *npm*

### Reproduction

In here we solved the `in` operation check https://github.com/micropython/micropython/pull/17604 but if any libraries tries to read the stringified version of a reference we have the same issue via the `get` proxy trap.

```js
function test(value) {
  return Object.prototype.toString.call(value);
}
```

```python
import js
js.test({})
```

Result:

```
RuntimeError: Aborted(Assertion failed: stringToUTF8Array expects a string (got symbol))
```

### Expected behaviour

We covered `Symbol.iterator` we should cover also `Symbol.toStringTag` as that's implicitly retrieved when `Object.prototype.toString.call(ref)` happens, which is a very common way to retrieve the *kind* of the reference as it returns:

* `[object Object]`
* `[object Array]`
* `[object Null]`
* `[object Function]`
* `[object Anything]`

This practice is particularly useful when unknown kinds are around and any serializer would like to guess how to handle these, and it's currently breaking a specific PyScript use case which is also pretty common when used in IoT contrained environments.

### Observed behaviour

An error is throws every single time.

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by WebReflection**
### Summary

This MR fixes https://github.com/micropython/micropython/issues/17657 by guarding against implicit unknown symbols accessed directly by specific JS native APIs.

### Testing

Added a new `get` proxy trap focused test that would throw otherwise with current MicroPython when `Object.prototype.toString.call(pyProxy)` happens, returning `null` just like the `then` case would for any symbol that is not `Symbol.iterator`.

### Trade-offs and Alternatives

The `typeof` operator is the fastest check JS offers for primitive types so there are not many side-effects or trafe-offs in here, just better runtime handling of unexpected symbol access that both 3rd party libraries or native JS APIs would regularly perform.

The only alternative approach is to return `undefined` which could be returned for `then` case too but neither of these actually matter as both `then` and `Symbol.toStringTag` or others are implicit via `Reflect` so that returning `null` is still OK, yet if anyone checks strictly against `undefined` that might fail but it's a very edge/uncommon use case to consider, so that changes in here are minimal.

### CODE REVIEW

File: ports/webassembly/objpyproxy.js [hunk 1]
```diff
@@ -169,30 +169,33 @@ const py_proxy_handler = {
...
-                while (true) {
-                    const valid = Module.ccall(
-                        "proxy_c_to_js_iternext",
-                        "number",
-                        ["number", "pointer"],
-                        [iter_ref, value],
-                    );
-                    if (!valid) {
-                        break;
+        if (typeof prop !== "string") {
```
Comment (dpgeorge) [inline ports/webassembly/objpyproxy.js]: Is it worth moving this if-block up to the top of this `get()` function?  Then if it fails we know `prop` is a string and it makes sense to test it against known strings like `_ref` and `then`.

This could maybe make the JS code slightly faster?

File: tests/ports/webassembly/py_proxy_get.mjs [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+mp.runPython(`
+x = {"a": 1}
+`);
+
+const x = mp.globals.get("x");
+console.log(x.a === 1);
+console.log(x.b === undefined);
+console.log(typeof x[Symbol.iterator] === "function");
+console.log(Object.prototype.toString.call(x) === "[object Object]");
```
Comment (dpgeorge) [inline tests/ports/webassembly/py_proxy_get.mjs]: Is there are simpler test to do here, maybe mirror `py_proxy_has.mjs`:
```js
console.log(x[Symbol.toStringTag]);
```
?

To me, that makes it easier to see exactly what is being tested here (namely, not-a-string as index).

**Comment by dpgeorge** [comment]
> The only alternative approach is to return `undefined`

I also thought this might be better, since it matches the JS side, eg:
```js
$ node
> {'0':1}[Symbol.toStringTag]
undefined
```
But I guess `null` is acceptable as your reasoning shows.

File: tests/ports/webassembly/py_proxy_get.mjs (hunk 2 above)
Comment (WebReflection) [reply tests/ports/webassembly/py_proxy_get.mjs]: I am not sure a comment would help but the reason for that test verbosity is to be sure that if JS APIs implicitly access unknown symbols these are handled and `toString.call(ref)` is a classic example of such implicit access but you are right it's not clear although that `console.log` would return `null` which is confusing indeed to me

File: ports/webassembly/objpyproxy.js (hunk 1 above)
Comment (WebReflection) [reply ports/webassembly/objpyproxy.js]: yes and no ... direct strict equality comparison is faster than `typeof` so I was trying to fallback gracefully for those `_ref` and `then` use cases ... true that `then` is an indirect edge-case but I wasn't sure about how much `_ref` access is needed so that I think check against `_ref` should be on top, for perf reasons, then we can check for `typeof` but at that point it'd be just moving `then` check after ... not much gain?

**Comment by WebReflection** [comment]
> But I guess `null` is acceptable as your reasoning shows.

if I change `null` in there I gotta change `null` for `then` too as that also reflects JS better and I am not sure why it was `null` in the first place?

```js
$ node
> ({'0':1}.then)
undefined
```

File: tests/ports/webassembly/py_proxy_get.mjs (hunk 2 above)
Comment (WebReflection) [reply tests/ports/webassembly/py_proxy_get.mjs]: P.S. also I cannot check against `typeof` because returning `null` will print out `object` which is not the case, it's indeed exactly `undefined` ... you know what? I am on it, still I think `_ref` is accessed tons of times so it should be on top of the filters

**Comment by WebReflection** [comment]
@dpgeorge in latest push we have:

* `_ref` still with fast/priority access
* `then` and symbols aggregated as fallback for `undefined` (instead of `null`) ... an extra check is done for strict equality check against `Symbol.iterator`
* more readable test that explicitly access an unknown symbol and also checks against `then` (I think that was a nice to have)

anything else I should change?

- - -

**edit** ... well, I could just `return;` instead of `return undefined;` ... I don't think it matters and maybe for readability sake (or "*greppability*") that `return undefined;` is just fine?

**Review by dpgeorge — APPROVED** [review]
This looks good now, thanks for updating!

**Comment by dpgeorge** [comment]
> I don't think it matters and maybe for readability sake (or "_greppability_") that `return undefined;` is just fine?

`return undefined` is better, especially if you're not used to JS like me :)

**Comment by WebReflection** [comment]
thanks @dpgeorge , any chance this can make it to npm too?

**Comment by dpgeorge** [comment]
> any chance this can make it to npm too?

Yes, I'll do that soon.

**Comment by dpgeorge** [comment]
Now published to npmjs: https://www.npmjs.com/package/@micropython/micropython-webassembly-pyscript/v/1.26.0-preview-386
