### PR TITLE
py/objint_longlong: Fix left shift of negative values.

### LINKED ISSUE #17702: -fsanitizer=undefined diagnostics with longlong
### Port, board and/or hardware

unix port, longlong variant

### MicroPython version

local version based on v1.25.0-387-g17fbc5abdc

### Reproduction

1. Modify `tools.ci.sh` to update the longlong build to include ubsan: 
    ```function ci_unix_longlong_build {
    ci_unix_build_helper VARIANT=longlong MICROPY_USE_COMPILER_PLUGIN=gcc \
    CFLAGS_EXTRA="-fsanitize=undefined -fno-sanitize=nonnull-attribute" LDFLAGS_EXTRA="-fsanitize=undefined -fno-sanitize=nonnull-attribute"
}
```
2. `(set -e; . tools/ci.sh; ci_unix_longlong_build; ci_unix_longlong_run_tests)`

### Expected behaviour

Tests succeed

### Observed behaviour

There are failures. Typical failure:
```
FAILURE /home/jepler/src/micropython/tests/results/basics_int_64_basics.py
--- /home/jepler/src/micropython/tests/results/basics_int_64_basics.py.exp	2025-07-17 12:00:04.723931234 -0500
+++ /home/jepler/src/micropython/tests/results/basics_int_64_basics.py.out	2025-07-17 12:00:04.727931280 -0500
@@ -117,6 +117,7 @@
 0
 0
 left shift negative
+../../py/objint_longlong.c:215:30: runtime error: left shift of negative value -10000000000000000
 -10000000000000000
 -10000000000000001
 -10000000000000002

```

```
4 tests failed: basics/int_64_basics.py micropython/viper_ptr32_store_boundary.py micropython/viper_ptr8_store_boundary.py micropython/viper_ptr16_store_boundary.py
```

### Additional Information

It might be a nice to add sanitizer builds of longlong (& nanbox?).

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Closes #17702, thanks to @jepler for running these additional checks.

* The overflow check for 'longlong' representation left shift added in #16953 was wrong, and depended on UB. Rewrote to be the same as the small int left shift overflow check.
* Skip the viper "boundary" store tests if arbitrary integer support is disabled, these tests depend on generating very long integers and then truncating them.

Note: First version of this PR enabled UBSan for longlong tests, but this surfaced another issue so has been spun out to #17735.

### Testing

* Re-ran unix port (with UBSan), observed tests pass and no errors.

### Trade-offs and Alternatives

* The viper "boundary" store tests could probably be rewritten to also work withouth arbitrary precision integers, but relatively fiddly to do so.

### CODE REVIEW

**Comment by projectgus** [comment]
Hmm, so running the `longlong` tests with UBSan I get two failures like this:

```
 --- /home/runner/work/micropython/micropython/tests/results/extmod_vfs_rom.py.exp	2025-07-22 01:24:29.075299604 +0000
+++ /home/runner/work/micropython/micropython/tests/results/extmod_vfs_rom.py.out	2025-07-22 01:24:29.075299604 +0000
@@ -1 +1,13 @@
-SKIP
+Traceback (most recent call last):
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 489, in <module>
+  File "/home/runner/work/micropython/micropython/lib/micropython-lib/python-stdlib/unittest/unittest/__init__.py", line 464, in main
+  File "/home/runner/work/micropython/micropython/lib/micropython-lib/python-stdlib/unittest/unittest/__init__.py", line 269, in run
+  File "/home/runner/work/micropython/micropython/lib/micropython-lib/python-stdlib/unittest/unittest/__init__.py", line 254, in run
+  File "/home/runner/work/micropython/micropython/lib/micropython-lib/python-stdlib/unittest/unittest/__init__.py", line 420, in _run_suite
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 166, in setUpClass
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 145, in make_romfs
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 136, in _make_romfs
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 115, in mkfile
+  File "/home/runner/work/micropython/micropython/tests/extmod/vfs_rom.py", line 80, in _encode_uint
+RuntimeError: maximum recursion depth exceeded
```

(I don't see these locally, but I have a different gcc locally.)

This looks a lot like the problem @koxudaxi was describing in #17649...

**Comment by projectgus** [comment]
Have pulled out the CI change to its own PR.

File: py/objint_longlong.c [hunk 1]
```diff
@@ -208,14 +208,16 @@ mp_obj_t mp_obj_int_binary_op(mp_binary_op_t op, mp_obj_t lhs_in, mp_obj_t rhs_i
...
             }
-            result = lhs_val << (int)rhs_val;
-            // Left-shifting of negative values is implementation defined in C, but assume compiler
-            // will give us typical 2s complement behaviour unless the value overflows
-            overflow = rhs_val > 0 && ((lhs_val >= 0 && result < lhs_val) || (lhs_val < 0 && result > lhs_val));
+            overflow = rhs_val >= (sizeof(long long) * MP_BITS_PER_BYTE)
+                || lhs_val > (LLONG_MAX >> rhs_val)
+                || lhs_val < (LLONG_MIN >> rhs_val);
+            if (!overflow) {
+                result = (unsigned long long)lhs_val << rhs_val;
```
Comment (dpgeorge) [inline py/objint_longlong.c]: Does this need a cast to unsigned?  `lhs_val` can still be negative here, but that should be OK.

File: tests/micropython/viper_ptr16_store_boundary.py [hunk 2]
```diff
@@ -1,5 +1,11 @@
 # Test boundary conditions for various architectures
 
+try:
+    int("0x10000000000000000", 16)
+except:
+    print("SKIP")  # No support for >64-bit integers
+    raise SystemExit
```
Comment (dpgeorge) [inline tests/micropython/viper_ptr16_store_boundary.py]: Instead of this, could rename the test to end with `_intbig.py`.  Eg following `tests/micropython/viper_misc_intbig.py` and `tests/micropython/viper_const_intbig.py` etc.

**Comment by yoctopuce** [comment]
Another option to fix the overflow check would be:
```c
if ((int)rhs_val > 62) {
    overflow = 1;
} else {
    rhs_val = 1ll << (int)rhs_val;
    overflow = mp_mul_ll_overflow(lhs_val, rhs_val, &result);                
}
```
I am not sure which one would generate the shortest code, given that the compiler might be able to merge the call to `mp_mul_ll_overflow` with the code in `MP_BINARY_OP_MULTIPLY`

File: py/objint_longlong.c (hunk 1 above)
Comment (projectgus) [reply py/objint_longlong.c]: It's needed, that was actually the mistake I made in the first version: Left shift of negative values is UB!

(Correctness of this version, and of the small int left shift it's based on, depends on the signed int representation being 2s complement - but that's a reasonable assumption.)

File: tests/micropython/viper_ptr16_store_boundary.py (hunk 2 above)
Comment (projectgus) [reply tests/micropython/viper_ptr16_store_boundary.py]: Oh of course! Thanks

**Comment by projectgus** [comment]
> Another option to fix the overflow check would be:
> 
> ```c
> if ((int)rhs_val > 62) {
>     overflow = 1;
> } else {
>     rhs_val = 1ll << (int)rhs_val;
>     overflow = mp_mul_ll_overflow(lhs_val, rhs_val, &result);                
> }
> ```
> 
> I am not sure which one would generate the shortest code, given that the compiler might be able to merge the call to `mp_mul_ll_overflow` with the code in `MP_BINARY_OP_MULTIPLY`

Neat idea! I tried it, but unfortunately the code size is still a little bigger:

(Building the Zephyr qemu cortex-m3 board as `west build -b qemu_cortex_m3 ~/micropython/ports/zephyr -- -DCONF_FILE=prj_minimal.conf`)

* master - 114068
* this PR - 114120
* calling mp_mul_overflow - 114192

I'm guessing either the calls can't be merged, or marshalling the values is still more work than doing the comparisons required in this version.

File: py/objint_longlong.c (hunk 1 above)
Comment (dpgeorge) [reply py/objint_longlong.c]: Ah, OK.

**Review by dpgeorge — APPROVED** [review]
