### PR TITLE
unix/main: Ensure atexit function is called on sys.exit() with -m <module>.

### LINKED ISSUE #18103: atexit function not executed at `micropython -m <module>`
### Port, board and/or hardware

Unix

### MicroPython version

MicroPython v1.26.1 on 2025-09-13; linux [GCC 14.2.0] version

### Reproduction

`a.py`:

```
import sys

def onexit():
    print('Exiting...')

sys.atexit(onexit)
sys.exit(0)
```

Running as a module:

```sh
micropython -m a
```

The MicroPython process was exited immediately without printing anything.

### Expected behaviour

It should prints:
```
Exiting...
```

### Observed behaviour

Run as a script (OK):
```sh
micropython a.py
```
prints:
```
Exiting...
```

---

without `sys.exit(0)` (OK):
```sh
micropython -m a
```
prints:
```
Exiting...
```

---

`-m` with `sys.exit(0)` (BUG):
```sh
micropython -m a
```
prints:
```
```

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by MikeWang000000**
### Summary

Fixes #18103.

Previously, when running `micropython -m <module>` and the module called sys.exit(), the registered atexit function was not executed. This was due to sys.exit() raising a SystemExit exception, which bypassed the atexit handler. This change fixes the issue so that the atexit function is properly invoked when exiting via sys.exit().

Additionally, following the pattern in execute_from_lexer, mp_hal_set_interrupt_char() and mp_handle_pending() handling were added to ensure that the atexit function is also executed when the user exits via Ctrl-C.

### Testing

Tested on Linux.

a.py:
```
import sys, time

def onexit():
    print('Exiting...')

sys.atexit(onexit)
sys.exit(0)  # or time.sleep(1000) and press Ctrl-C
```

```
micropython -m a
```

### CODE REVIEW

File: ports/unix/main.c [hunk 1]
```diff
@@ -669,12 +669,18 @@ MP_NOINLINE int main_(int argc, char **argv) {
...
+                    mp_hal_set_interrupt_char(-1);
+                    mp_handle_pending(true);
                     nlr_pop();
                 } else {
                     // uncaught exception
-                    return handle_uncaught_exception(nlr.ret_val) & 0xff;
+                    mp_hal_set_interrupt_char(-1);
+                    mp_handle_pending(false);
+                    ret = handle_uncaught_exception(nlr.ret_val) & 0xff;
+                    goto cleanup;
```
Comment (dlech) [inline ports/unix/main.c]: Does this break the `inspect` option? Why not just `break` here instead of `goto`?

Comment (MikeWang000000) [reply ports/unix/main.c]: Sorry I didn't investigate what `MICROPYINSPECT` does. The code has now been corrected.

Comment (dlech) [reply ports/unix/main.c]: No worries. That is why we do code review. :smile:

**Comment by dpgeorge** [comment]
Thanks for the fix, this looks good.  I verified the behaviour locally and it works well.

I also added 2 tests to this PR to make sure the issue does not regress.  See what you think.

**Review by MikeWang000000 — COMMENTED** [review]
Looks good!

**Review by dpgeorge — APPROVED** [review]
