### PR TITLE
esp32: Improve machine.SDCard support on newer chips

### LINKED ISSUE #8514: In esp32-s3, cannot use (machine. Sdcard class)
Call machine.Sdcard (slot = 2, miso = pin (36), MoSi = pin (35), SCK = pin (37), CS = pin (38)) on espressif esp32-s3 development board reports an error:

_[0;31mE (8250) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
[0;31mE (8250) sdspi_host: spi_bus_initialize failed with rc=0x102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
OSError: (-258, 'ESP_ERR_INVALID_ARG')_

modify  micropython/ports/esp32/machine_sdcard.c  Line 214，machine.sdcard() call can be resumed
_.dma_channel = 2----------->.dma_channel = 3_

Because in ESP-IDF dma_channel==3 Indicates automatic assignment DMA,Otherwise, the machine.Sdcard() will not work properly

### LINKED ISSUE #12447: SDCard not supported for ESP32C3
I have a custom ESP32C3 board that has an SD Card on it. I can easily run SD Card functions in Arduino with it but when I put micropython on it using the latest release, SDCard isn't even found when you try to call it. It's not my first time compiling my own board though so went into ports/esp32/boards/ESP32_GENERIC_C3/mpconfigboard.h (Using v5.1 of esp-idf and a current copy of this repository), changed `#define MICROPY_HW_ENABLE_SDCARD            (0)` to `#define MICROPY_HW_ENABLE_SDCARD            (1)` and then changed ports/esp32/machine_sdcard.c to the proper pins of  sck=4 miso=5 and mosi=6 (also cs=1 in my case). I get the following errors...

/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:124:20: error: 'SPI3_HOST' undeclared here (not in a function); did you mean 'SPI2_HOST'?
  124 |         .host_id = SPI3_HOST,
      |                    ^~~~~~~~~
      |                    SPI2_HOST
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c: In function 'machine_sdcard_make_new':
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:238:35: error: implicit declaration of function 'SDMMC_HOST_DEFAULT'; did you mean 'SDSPI_HOST_DEFAULT'? [-Werror=implicit-function-declaration]
  238 |         sdmmc_host_t _temp_host = SDMMC_HOST_DEFAULT();
      |                                   ^~~~~~~~~~~~~~~~~~
      |                                   SDSPI_HOST_DEFAULT
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:238:35: error: invalid initializer
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:295:9: error: unknown type name 'sdmmc_slot_config_t'
  295 |         sdmmc_slot_config_t slot_config = SDMMC_SLOT_CONFIG_DEFAULT();
      |         ^~~~~~~~~~~~~~~~~~~
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:295:43: error: implicit declaration of function 'SDMMC_SLOT_CONFIG_DEFAULT'; did you mean 'SDSPI_DEVICE_CONFIG_DEFAULT'? [-Werror=implicit-function-declaration]
  295 |         sdmmc_slot_config_t slot_config = SDMMC_SLOT_CONFIG_DEFAULT();
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           SDSPI_DEVICE_CONFIG_DEFAULT
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:136:11: error: request for member 'gpio_cd' in something not a structure or union
  136 |     config.pin_var = machine_pin_get_id(arg_vals[arg_id].u_obj)
      |           ^
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:301:9: note: in expansion of macro 'SET_CONFIG_PIN'
  301 |         SET_CONFIG_PIN(slot_config, gpio_cd, ARG_cd);
      |         ^~~~~~~~~~~~~~
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:136:11: error: request for member 'gpio_wp' in something not a structure or union
  136 |     config.pin_var = machine_pin_get_id(arg_vals[arg_id].u_obj)
      |           ^
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:302:9: note: in expansion of macro 'SET_CONFIG_PIN'
  302 |         SET_CONFIG_PIN(slot_config, gpio_wp, ARG_wp);
      |         ^~~~~~~~~~~~~~
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:306:24: error: request for member 'width' in something not a structure or union
  306 |             slot_config.width = width;
      |                        ^
/home/brad/esp-idf/micropython/ports/esp32/machine_sdcard.c:312:23: error: implicit declaration of function 'sdmmc_host_init_slot' [-Werror=implicit-function-declaration]
  312 |         check_esp_err(sdmmc_host_init_slot(self->host.slot, &slot_config));
      |                       ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/brad/esp-idf/micropython/ports/esp32/build-ESP32_GENERIC_C3/log/idf_py_stderr_output_1718238 and /home/brad/esp-idf/micropython/ports/esp32/build-ESP32_GENERIC_C3/log/idf_py_stdout_output_1718238
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [Makefile:62: all] Error 1

Like I said, SD works perfectly fine in Arduino so I know there's no hardware issue or anything like that because I know I'm calling the proper pins. When I change things back to `#define MICROPY_HW_ENABLE_SDCARD            (0)` everything compiles fine, but obviously there's no way to use an sd card without it set to 1. It's also obvious there are no definitions in machine_sdcard.c to support the ESP32C3, but I don't know how to fix it aside from changing to the necessary SPI pins.

### LINKED ISSUE #16526: ESP32-S3 SDCard(width=4) uses undocumented hard-coded pin assignments
### Port, board and/or hardware

esp32 port - ESP32-S3

### MicroPython version

MicroPython v1.25.0-preview.114.gbdda91fe7 on 2025-01-05

### Reproduction
`
import machine
import os
import esp
esp.osdebug(True, esp.LOG_VERBOSE)

try:
    sd = machine.SDCard(slot=1, width=4)
    os.mount(sd, "/sd")
    print("SD card mounted successfully.")
    
    print("Contents of the SD card:")
    for filename in os.listdir("/sd"):
        print(filename)
except Exception as e:
    print("Error initializing SD card:", e)
`

### Expected behaviour

Print a list of files on the SD card.

### Observed behaviour

import sd_test
I (809804) gpio: GPIO[14]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (809854) gpio: GPIO[15]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (809854) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (809864) gpio: GPIO[4]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (809874) gpio: GPIO[12]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (809884) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (809924) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
Error initializing SD card: 16
>>>

### Additional Information

I have tried everything to get an SD card to work like it does in sdmmc example for esp-idf (https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card/sdmmc). If I run this example in esp-idf, everything works perfectly fine right out of the box. It literally took 3 seconds to set up. After 7 hours of work and research, I simply can't get the sd card to work in micropython. Not SPI, not MMC, nothing. Micropython is supposed to be built on top of esp-idf so I would assume it should be just as easy. I looked at the SDCard class (https://docs.micropython.org/en/latest/library/machine.SDCard.html) and found that I should be able to configure the pins in mpconfigboard.h, to which I tried `
#define USDHC_DUMMY_PIN NULL , 0
#define MICROPY_USDHC1 \
  { \
        .cmd   = { 35}, \
        .clk   = { 36 }, \
        .cd_b  = { USDHC_DUMMY_PIN },\
        .data0 = { 37 },\
        .data1 = { 38 },\
        .data2 = { 33 },\
        .data3 = { 34 },\
  }` 
like it says, but it still tries to use ESP32 pins when I call the machine.SDCard(), like it also says to do. If I try to add the pins inside machine.SDCard() it says I have too many arguments. At one point I found someone with the same complaint but it had literally no information aside from "modify machine_sdcard.c" with no information on how to modify it and honestly I find that an absolutely terrible idea. Why modify the entire port to make a single board work, that should work from the beginning by default? I have no problem modifying a board to make it work but to me, modifying the port makes no sense unless it gets modified for everybody. I have spent 7 hours trying to get an sd card to work in micropython when it took 3 seconds to get to work in esp-idf. The only information I find are complaints about the same thing but no answers. This is insane.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Updating the esp32 port `machine.SDCard` support for other chips:

* Added support for configuring pins in SD/MMC mode on ESP32-S3. Closes #8514. Closes #16526.
* Added support for SDCard in SPI mode on ESP32-S2, C3 and C6. This is a little restrictive on C3 and C6 as they only have one available SPI bus, so can't use this and `machine.SPI` together. Have enabled on all boards by default (the code size impact is about 4KB).
* Explicitly disable slot 0 on original ESP32 (and document this). There are effectively zero ESP32 boards in the world that can use slot 0 for SDMMC.

*This work was funded through GitHub sponsors*

### TODO

* [x] Final docs pass
* ~~[ ] ESP32-S3 SDCard object should print the additonal pin config~~ *EDIT: Actually SDCard has no print support on esp32, so leaving this off.*

### Testing

Manual testing with SD card breakout module:

* [x] ESP32-S3 in SDMMC mode with custom pins.
* [x] ESP32-S3 in SPI mode on both hosts.
* [x] ESP32-C3 in SPI mode.
* [x] ESP32-C6 in SPI mode. 
* [x] ESP32-S2 in SPI mode on both hosts.
* [x] ESP32 in SDMMC and SPI modes.

~~Note that testing is easier if cherry-picking #16700 fix into the branch.~~

### Trade-offs and Alternatives

* Could drop the commit that enables SDCard on SPI-only chips if preferable, and update docs to suit. Although on balance I think it's still potentially useful.

### CODE REVIEW

**Review by dpgeorge — APPROVED** [review]
A really nice clean up, and improvement for S3 allowing to set data pins.  Thanks!

Tested on ESP32, using `vfs.mount(machine.SDCard(), "/sd")` worked out-of-the-box.

File: ports/esp32/machine_sdcard.c [hunk 1]
```diff
@@ -307,9 +381,36 @@ static mp_obj_t machine_sdcard_make_new(const mp_obj_type_t *type, size_t n_args
...
+        #if SOC_SDMMC_USE_GPIO_MATRIX
+        // Optionally configure all the SDMMC pins, if chip supports this
+        SET_CONFIG_PIN(slot_config, clk, ARG_sck); // reuse SPI SCK for CLK
+        SET_CONFIG_PIN(slot_config, cmd, ARG_cmd);
+        if (arg_vals[ARG_data].u_obj != mp_const_none) {
+            mp_obj_t *data_vals;
+            size_t data_len;
+            mp_obj_get_array(arg_vals[ARG_data].u_obj, &data_len, &data_vals);
+            if (data_len != width) {
+                mp_raise_msg_varg(&mp_type_ValueError, MP_ERROR_TEXT("data argument length must match width %d"), width);
```
Comment (dpgeorge) [inline ports/esp32/machine_sdcard.c:393]: I added the missing `MP_ERROR_TEXT` here.
