### PR TITLE
py/builtinevex: Handle invalid filenames for execfile.

### LINKED ISSUE #12522: Null pointer dereference in mp_reader_new_file
# Description

We found a null-dereference in the UNIX port version. All PoCs involve `builtins.execfile()` and crash in `mp_reader_new_file` eventually. We've attached three PoCs and their stack trace from ASAN.

[poc.zip](https://github.com/micropython/micropython/files/12729197/poc.zip)

# Proof of Concept

```
$ # build unix port with ASAN, at the root source code directory.
$ export CC=clang
$ export CXX=clang++
$ export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
$ export CXXFLAGS=$CFLAGS
$ export LDFLAGS=$CFLAGS
$ export DEBUG=1
$ make -C mpy-cross -j
$ make -C ports/unix -j all lib
$
$ # run a poc.
$ export ASAN_OPTIONS="detect_leaks=0"
$ ./ports/unix/build-standard/micropython <poc_file>
```

# Environment

Ubuntu 20.04
Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Memory: 64 GB

# Affected Version

v1.20.0 (commit a3862e726, latest as of 2023-09-26)
v1.20.0 (commit 813d559bc, 2023-06-19)

# Question

We actually found many more crashes with ASAN other than this (including buffer-overflow), but we'd need some advice from `micropython` maintainers before posting issues for all of them.

  1) Do you also consider ASAN crashes through the UNIX port version relevant?
  2) How do you prefer accepting buffer-overflow cases? (via e-mail or via here) We haven't verified their exploitability.

Please let me report the rest of the crashes following your advice. Thank you very much for maintaining `micropython`.

### PR DESCRIPTION
**Pull request by jimmo**
Fixes #12522.

If a non-string buffer was passed to execfile, then it would be passed as a non-null-terminated char* to mp_lexer_new_from_file.

This changes mp_lexer_new_from_file to take a qstr instead (as in almost all cases a qstr will be created from this input anyway).

This now makes execfile require a string (not generic buffer) argument, which is probably a good fix to make anyway.

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by dpgeorge** [comment]
> This changes mp_lexer_new_from_file to take a qstr instead (as in almost all cases a qstr will be created from this input anyway).

Is this necessary, or even a good idea (in terms of code size and/or memory allocation)?

Regardless, IMO there should be two separate commits: one for the fix and one for the qstr change.

**Comment by jimmo** [comment]
> Is this necessary, or even a good idea (in terms of code size and/or memory allocation)?

It's +4 bytes (we were going to need this anyway to check the input). No change to memory allocation - a str and a qstr were already being allocated anyway.
> 
> Regardless, IMO there should be two separate commits: one for the fix and one for the qstr change.

The qstr change _is_ the fix.

File: py/builtinevex.c [hunk 1]
```diff
@@ -136,17 +136,18 @@ STATIC mp_obj_t eval_exec_helper(size_t n_args, const mp_obj_t *args, mp_parse_i
...
-    // Extract the source code.
-    mp_buffer_info_t bufinfo;
-    mp_get_buffer_raise(args[0], &bufinfo, MP_BUFFER_READ);
 
     // create the lexer
     // MP_PARSE_SINGLE_INPUT is used to indicate a file input
     mp_lexer_t *lex;
     if (MICROPY_PY_BUILTINS_EXECFILE && parse_input_kind == MP_PARSE_SINGLE_INPUT) {
-        lex = mp_lexer_new_from_file(bufinfo.buf);
+        lex = mp_lexer_new_from_file(mp_obj_str_get_qstr(args[0]));
```
Comment (dpgeorge) [inline py/builtinevex.c:144]: Couldn't the fix simply be to use `mp_obj_str_get_str` here?

File: py/builtinimport.c [hunk 2]
```diff
@@ -232,13 +232,15 @@ STATIC void do_load(mp_module_context_t *module_obj, vstr_t *file) {
 
     #endif // MICROPY_MODULE_FROZEN
 
+    qstr file_qstr = qstr_from_str(file_str);
```
Comment (dpgeorge) [inline py/builtinimport.c:235]: For the case where it's importing a .mpy file, this now interns the filename when it didn't before.

Comment (jimmo) [reply py/builtinimport.c:240]: It always interns the filename as it sets the `__file__` attribute to the same value in `do_execute_raw_code`. This is true for all imports (.py, .mpy, frozen). I've updated the PR to make this more explicit (and save it having to search for the now-already-interned value).

Technically `__file__` might be disabled, but it is enabled at level=core.

File: py/builtinevex.c (hunk 1 above)
Comment (jimmo) [reply py/builtinevex.c:144]: Yes but now you have two copies of the string. One made here, another made in `mp_reader_new_file`.

Also one day we might want to not make str and/or qstr null terminated, so I'm always hesitant to make this dependency worse.

File: py/builtinimport.c (hunk 2 above)
Comment (dpgeorge) [reply py/builtinimport.c:240]: You're right, `do_execute_raw_code` is interning the filename... it just seems a bit off to me that you now need to pass a qstr as a filename everywhere (for lexing, etc) instead of a const-char-*.  But I guess that's the way everything is structured, and the reason for that is so that tracebacks can include the filename easily.

File: py/builtinevex.c (hunk 1 above)
Comment (dpgeorge) [reply py/builtinevex.c:144]: Well, `mp_obj_str_get_str` doesn't create anything, it just returns a pointer to the already-null-terminated data.  So using that function would be a very simple fix for this problem, and not allocate any additional RAM.  Then the larger qstr change is an optimisation.
